[lint]
# Generated list of currently failing rules from ruff check --statistics
ignore = [
    "B005",
    "B006",
    "B018",
    "B020",
    "B026",
    "BLE001",
    "C402",
    "C403",
    "C404",
    "C405",
    "C408",
    "C411",
    "C414",
    "DTZ004",
    "DTZ005",
    "DTZ006",
    "DTZ007",
    "E722",
    "EXE001",
    "EXE002",
    "F401",
    "F402",
    "F601",
    "F633",
    "F811",
    "F821",
    "F841",
    "FLY002",
    "FURB163",
    "LOG015",
    "PERF102",
    "PERF402",
    "PLC0206",
    "PLC3002",
    "PLR1704",
    "PLR1722",
    "PLW0127",
    "PLW1510",
    "RUF012",
    "RUF015",
    "RUF046",
    "RUF059",
    "RUF100",
    "S110",
    "SIM101",
    "SIM102",
    "SIM103",
    "SIM115",
    "SIM118",
    "SIM210",
    "SIM401",
    "TRY002",
    "TRY004",
    "TRY201",
    "TRY203",
    "UP028",
    "UP030",
    "UP031",
    "UP036",
    "YTT201",
]

exclude = [
    "sdk/waf/waflib/**/*.py"
]