[lint]
# Generated list of currently failing rules from ruff check --statistics
ignore = [
    "B004",
    "B005",
    "B006",
    "B009",
    "B010",
    "B018",
    "B020",
    "B023",
    "B026",
    "BLE001",
    "C402",
    "C403",
    "C404",
    "C405",
    "C408",
    "C411",
    "C413",
    "C414",
    "C419",
    "DTZ003",
    "DTZ004",
    "DTZ005",
    "DTZ006",
    "DTZ007",
    "E722",
    "EXE001",
    "EXE002",
    "F401",
    "F402",
    "F541",
    "F601",
    "F633",
    "F811",
    "F821",
    "F841",
    "FLY002",
    "FURB105",
    "FURB122",
    "FURB129",
    "FURB163",
    "FURB166",
    "FURB167",
    "FURB188",
    "G010",
    "I001",
    "LOG015",
    "N999",
    "PERF102",
    "PERF402",
    "PIE790",
    "PIE807",
    "PIE808",
    "PIE810",
    "PLC0206",
    "PLC3002",
    "PLR0402",
    "PLR1704",
    "PLR1711",
    "PLR1722",
    "PLR1730",
    "PLR1736",
    "PLW0127",
    "PLW0602",
    "PLW0642",
    "PLW1508",
    "PLW1510",
    "RET501",
    "RUF012",
    "RUF015",
    "RUF019",
    "RUF022",
    "RUF023",
    "RUF046",
    "RUF051",
    "RUF059",
    "RUF100",
    "S102",
    "S110",
    "S112",
    "SIM101",
    "SIM102",
    "SIM103",
    "SIM113",
    "SIM114",
    "SIM115",
    "SIM118",
    "SIM201",
    "SIM210",
    "SIM223",
    "SIM401",
    "SIM905",
    "T100",
    "TRY002",
    "TRY004",
    "TRY201",
    "TRY203",
    "UP004",
    "UP008",
    "UP009",
    "UP010",
    "UP012",
    "UP018",
    "UP024",
    "UP026",
    "UP028",
    "UP030",
    "UP031",
    "UP032",
    "UP034",
    "UP035",
    "UP036",
    "UP041",
    "UP045",
    "W605",
    "YTT201",
]