/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#include <pbl/crc/crc.h>
#include <pbl/drivers/crc.h>

// Nybble-wide lookup table, generated by crc32_lut.py
static const uint32_t s_lut[16] = {
  0x00000000, 0x1db71064, 0x3b6e20c8, 0x26d930ac, 0x76dc4190, 0x6b6b51f4, 0x4db26158, 0x5005713c,
  0xedb88320, 0xf00f9344, 0xd6d6a3e8, 0xcb61b38c, 0x9b64c2b0, 0x86d3d2d4, 0xa00ae278, 0xbdbdf21c,
};

static uint32_t prv_crc32_sw(uint32_t crc, const uint8_t *bytes, size_t len) {
  crc = ~crc;
  while (len--) {
    crc = (crc >> 4) ^ s_lut[(crc ^ *bytes) & 0x0f];
    crc = (crc >> 4) ^ s_lut[(crc ^ (*bytes >> 4)) & 0x0f];
    bytes++;
  }
  return ~crc;
}

uint32_t pbl_crc32(uint32_t crc, const void *data, size_t len) {
  if (data == NULL) {
    return 0;
  }

  const uint8_t *bytes = data;
#if defined(CONFIG_CRC_HW_ACCEL)
  if (len >= CONFIG_CRC_HW_MIN_LEN) {
    const size_t done = pbl_crc_hw_crc32(&crc, bytes, len);
    bytes += done;
    len -= done;
  }
#endif
  return prv_crc32_sw(crc, bytes, len);
}
