/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#include <pbl/crc/crc.h>
#include <pbl/drivers/crc.h>

// Nybble-wide lookup table for the non-reflected CRC-32 polynomial, generated by
// crc32_legacy_lut.py
static const uint32_t s_lut[16] = {
  0x00000000, 0x04c11db7, 0x09823b6e, 0x0d4326d9, 0x130476dc, 0x17c56b6b, 0x1a864db2, 0x1e475005,
  0x2608edb8, 0x22c9f00f, 0x2f8ad6d6, 0x2b4bcb61, 0x350c9b64, 0x31cd86d3, 0x3c8ea00a, 0x384fbdbd,
};

static uint32_t prv_byte(uint32_t reg, uint8_t byte) {
  reg = (reg << 4) ^ s_lut[((reg >> 28) ^ (byte >> 4)) & 0x0f];
  reg = (reg << 4) ^ s_lut[((reg >> 28) ^ byte) & 0x0f];
  return reg;
}

static uint32_t prv_words_sw(uint32_t reg, const uint8_t *bytes, size_t len) {
  for (; len >= 4; len -= 4, bytes += 4) {
    reg = prv_byte(reg, bytes[3]);
    reg = prv_byte(reg, bytes[2]);
    reg = prv_byte(reg, bytes[1]);
    reg = prv_byte(reg, bytes[0]);
  }
  return reg;
}

static uint32_t prv_words(uint32_t reg, const uint8_t *bytes, size_t len) {
#if defined(CONFIG_CRC_HW_ACCEL)
  if (len >= CONFIG_CRC_HW_MIN_LEN) {
    const size_t done = pbl_crc_hw_crc32_legacy(&reg, bytes, len);
    bytes += done;
    len -= done;
  }
#endif
  return prv_words_sw(reg, bytes, len);
}

void pbl_crc32_legacy_init(struct pbl_crc32_legacy *ctx) {
  *ctx = (struct pbl_crc32_legacy){
    .reg = 0xffffffff,
  };
}

void pbl_crc32_legacy_update(struct pbl_crc32_legacy *ctx, const void *data, size_t len) {
  const uint8_t *bytes = data;

  if (ctx->accumulated_length) {
    for (; ctx->accumulated_length < 3 && len; len--) {
      ctx->accumulator[ctx->accumulated_length++] = *bytes++;
    }
    if (ctx->accumulated_length == 3 && len) {
      const uint8_t word[4] = {
        ctx->accumulator[0], ctx->accumulator[1], ctx->accumulator[2], *bytes++
      };
      len--;
      ctx->reg = prv_words_sw(ctx->reg, word, sizeof(word));
      ctx->accumulated_length = 0;
    }
  }

  const size_t words_len = len & ~(size_t)3;
  ctx->reg = prv_words(ctx->reg, bytes, words_len);
  bytes += words_len;
  len -= words_len;

  for (; len; len--) {
    ctx->accumulator[ctx->accumulated_length++] = *bytes++;
  }
}

uint32_t pbl_crc32_legacy_finish(struct pbl_crc32_legacy *ctx) {
  if (ctx->accumulated_length) {
    for (int padding = 4 - ctx->accumulated_length; padding; padding--) {
      ctx->reg = prv_byte(ctx->reg, 0);
    }
    for (int i = 0; i < ctx->accumulated_length; ++i) {
      ctx->reg = prv_byte(ctx->reg, ctx->accumulator[i]);
    }
  }
  return ctx->reg;
}

uint32_t pbl_crc32_legacy(const void *data, size_t len) {
  struct pbl_crc32_legacy ctx;
  pbl_crc32_legacy_init(&ctx);
  pbl_crc32_legacy_update(&ctx, data, len);
  return pbl_crc32_legacy_finish(&ctx);
}
