#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

"""Build third_party/picolibc for the firmware's architecture.

picolibc is a Meson project of its own, but it needs a cross file the
firmware build cannot share: no crt0, no semihosting, and a 32-bit
__time_t. Rather than a subproject it is configured and built here, at
configure time, and the firmware links against the specs file it installs.
"""

import argparse
import os
import subprocess
import sys

OVERRIDE = """/* Generated by meson/libc/picolibc.py. */
#ifndef _PBL_PICOLIBC_MACHINE_OVERRIDE_H
#define _PBL_PICOLIBC_MACHINE_OVERRIDE_H
/* picolibc force-includes this into .S files too; C-only. */
#ifndef __ASSEMBLER__
typedef long __time_t;
#define __machine_time_t_defined
#endif
#endif
"""


def cross_compile_prefix(cc):
    """The toolchain prefix, from the compiler the firmware build found."""
    for part in cc:
        name = os.path.basename(part)
        if name.endswith("gcc"):
            return part[: -len("gcc")]
    sys.exit(f"Cannot derive the toolchain prefix from {cc}")


def write_cross_file(path, prefix, arch, override):
    flags = ", ".join(f"'{flag}'" for flag in list(arch) + ["-include", override])
    with open(path, "w") as f:
        f.write(
            f"""[binaries]
c = ['{prefix}gcc', {flags}, '-nostdlib']
cpp = ['{prefix}g++', {flags}, '-nostdlib']
ar = '{prefix}ar'
as = '{prefix}as'
nm = '{prefix}nm'
strip = '{prefix}strip'
[host_machine]
system = 'none'
cpu_family = 'arm'
cpu = 'arm'
endian = 'little'
[properties]
skip_sanity_check = true
"""
        )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["setup"])
    parser.add_argument("--source", required=True)
    parser.add_argument("--build", required=True)
    parser.add_argument("--install", required=True)
    parser.add_argument("--override", required=True)
    parser.add_argument("--cross", required=True)
    parser.add_argument("--meson", required=True)
    parser.add_argument("--ninja", required=True)
    parser.add_argument("--cc", nargs="+", required=True)
    parser.add_argument("--arch", nargs="*", default=[])
    args = parser.parse_args()

    os.makedirs(os.path.dirname(args.override), exist_ok=True)
    with open(args.override, "w") as f:
        f.write(OVERRIDE)

    write_cross_file(
        args.cross, cross_compile_prefix(args.cc), args.arch, args.override
    )

    # A single architecture, no crt0 or semihosting (the firmware supplies
    # its own startup and syscalls), C99 + long long formatted I/O, and one
    # global TLS block (per-task TLS is a separate integration).
    if not os.path.exists(os.path.join(args.build, "build.ninja")):
        print("Configuring picolibc", file=sys.stderr)
        subprocess.run(
            [
                args.meson, "setup", args.build, args.source,
                "--cross-file", args.cross,
                f"-Dspecsdir={args.install}/lib",
                f"--prefix={args.install}",
                "-Dmultilib=false",
                "-Dpicocrt=false",
                "-Dsemihost=false",
                "-Dtests=false",
                "-Dio-long-long=true",
                "-Dformat-default=long-long",
                "-Dthread-local-storage=false",
            ],
            check=True,
        )

    print("Building picolibc", file=sys.stderr)
    subprocess.run(
        [args.ninja, "-C", args.build, "install"], check=True, stdout=subprocess.DEVNULL
    )

    specs = os.path.join(args.install, "lib", "picolibc.specs")
    if not os.path.exists(specs):
        sys.exit("picolibc build did not produce picolibc.specs")


if __name__ == "__main__":
    main()
