/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

#include <stdarg.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include <pbl/kernel/compiler.h>

#include <console/dbgserial.h>
#include <system/die.h>
#include <system/reboot_reason.h>
#include <system/status_codes.h>

/**
 * @defgroup logging Logging
 * @ingroup subsys
 * @brief Leveled logging to the serial console (or PULSE) and to flash.
 *
 * Use the level-named macros: PBL_LOG_ERR() and PBL_LOG_WRN() for errors and warnings,
 * PBL_LOG_DBG() for routine lifecycle and state-transition messages, and PBL_LOG_INFO() only for
 * events that deserve attention in a default-level capture; code paths that can fire repeatedly
 * in normal use must not log at INFO. PBL_LOG_ALWAYS() is never filtered.
 *
 * Each source file can belong to a log module with a Kconfig level, generated by
 * @c subsys/logging/Kconfig.template.log_level; messages above the module level are compiled
 * out. Files without a module use @ref DEFAULT_LOG_LEVEL. A module built with
 * @c CONFIG_<module>_LOG_LEVEL_RUNTIME keeps all its messages and filters them at runtime, see
 * PBL_LOG_MODULE_LEVEL_SET().
 *
 * The async macros may queue the message when called from an interrupt or with interrupts or
 * the scheduler locked; the sync variants send it before returning in every context, for fault
 * paths. With @c CONFIG_LOG_HASHED the format strings are replaced by tokens at build time (see
 * @ref logging_log_hashing), which limits them to 7 conversions, 2 of them @c \%s, 32-bit
 * arguments and no @c \%\%.
 *
 * @note Do not mix @c \%s with @c \%x or @c \%X in one message; the log dehasher cannot decode
 * it. Split the message instead.
 *
 * @code{.c}
 * PBL_LOG_MODULE_DEFINE(my_service, CONFIG_MY_SERVICE_LOG_LEVEL);
 *
 * PBL_LOG_DBG("Connected, interval %u ms", interval_ms);
 * PBL_LOG_WRN("Write failed: %d", rc);
 * PBL_LOG_ERR("Bad header 0x%" PRIx32, hdr);
 * PBL_LOG_DBG("Peer %s", name);
 * @endcode
 *
 * Other files of the same module use PBL_LOG_MODULE_DECLARE() with the same arguments.
 * @{
 */

/**
 * @brief Expand a 64-bit value into two 32-bit arguments, high word first.
 *
 * Hashed logs only take 32-bit arguments; print the result with two conversions.
 *
 * @param x 64-bit value.
 */
#define SPLIT_64_BIT_ARG(x) (uint32_t)((x >> 32) & 0xFFFFFFFF), (uint32_t)(x & 0xFFFFFFFF)

/** @brief Size of the buffer a log message is formatted into, header included. */
#define LOG_BUFFER_LENGTH 128

/** @brief Minimum free stack, in bytes, to format a message; below it the message is replaced. */
#define LOGGING_MIN_STACK_FOR_SPRINTF 240
/** @brief Message logged instead when the stack is too full to format it. */
#define LOGGING_STACK_FULL_MSG ((const char *)" [STK FULL]")

/**
 * @brief Log a hashed message, possibly queued. Called by the PBL_LOG macros.
 *
 * @param packed_loghash Message token, see @ref logging_log_hashing.
 * @param ... Message arguments, 32 bits each.
 */
void pbl_log_hashed_async(const uint32_t packed_loghash, ...);

/**
 * @brief Log a hashed message, sent before returning. Called by the PBL_LOG_SYNC macros.
 *
 * @param packed_loghash Message token, see @ref logging_log_hashing.
 * @param ... Message arguments, 32 bits each.
 */
void pbl_log_hashed_sync(const uint32_t packed_loghash, ...);

/**
 * @brief pbl_log_hashed_async() for modules with a runtime level, bypassing the sink filters.
 *
 * @param packed_loghash Message token, see @ref logging_log_hashing.
 * @param ... Message arguments, 32 bits each.
 */
void pbl_log_hashed_filtered_async(const uint32_t packed_loghash, ...);
/**
 * @brief pbl_log_hashed_sync() for modules with a runtime level, bypassing the sink filters.
 *
 * @param packed_loghash Message token, see @ref logging_log_hashing.
 * @param ... Message arguments, 32 bits each.
 */
void pbl_log_hashed_filtered_sync(const uint32_t packed_loghash, ...);

/**
 * @brief Log a hashed message from another core, possibly queued.
 *
 * @param core_number Core number, already shifted to @ref PACKED_CORE_OFFSET.
 * @param packed_loghash Message token, see @ref logging_log_hashing.
 * @param ... Message arguments, 32 bits each.
 */
void pbl_log_hashed_core(const uint32_t core_number, const uint32_t packed_loghash, ...);

/**
 * @brief Log a hashed message from another core, with a va_list.
 *
 * @param async Whether the message may be queued.
 * @param core_number Core number, already shifted to @ref PACKED_CORE_OFFSET.
 * @param packed_loghash Message token, see @ref logging_log_hashing.
 * @param fmt_args Message arguments, 32 bits each.
 */
void pbl_log_hashed_vargs(const bool async, const uint32_t core_number,
                          const uint32_t packed_loghash, va_list fmt_args);

/**
 * @brief Log a message with a va_list, possibly queued.
 *
 * @param log_level Level, one of the @c LOG_LEVEL_ values.
 * @param src_filename Source file path.
 * @param src_line_number Source line number.
 * @param fmt printf-style format.
 * @param args Format arguments.
 */
void pbl_log_vargs(uint8_t log_level, const char *src_filename, int src_line_number,
                   const char *fmt, va_list args);

/**
 * @brief Log a message, possibly queued.
 *
 * Prefer the PBL_LOG macros, which filter by level and hash the format.
 *
 * @param log_level Level, one of the @c LOG_LEVEL_ values.
 * @param src_filename Source file path.
 * @param src_line_number Source line number.
 * @param fmt printf-style format.
 * @param ... Format arguments.
 */
void pbl_log(uint8_t log_level, const char *src_filename, int src_line_number, const char *fmt, ...)
    PBL_FORMAT_PRINTF(4, 5);

/**
 * @brief Log a message, sent before returning.
 *
 * @param log_level Level, one of the @c LOG_LEVEL_ values.
 * @param src_filename Source file path.
 * @param src_line_number Source line number.
 * @param fmt printf-style format.
 * @param ... Format arguments.
 */
void pbl_log_sync(uint8_t log_level, const char *src_filename, int src_line_number, const char *fmt,
                  ...) PBL_FORMAT_PRINTF(4, 5);

/**
 * @brief pbl_log() for modules with a runtime level, bypassing the sink filters.
 *
 * @param log_level Level, one of the @c LOG_LEVEL_ values.
 * @param src_filename Source file path.
 * @param src_line_number Source line number.
 * @param fmt printf-style format.
 * @param ... Format arguments.
 */
void pbl_log_filtered(uint8_t log_level, const char *src_filename, int src_line_number,
                      const char *fmt, ...) PBL_FORMAT_PRINTF(4, 5);

/**
 * @brief pbl_log_sync() for modules with a runtime level, bypassing the sink filters.
 *
 * @param log_level Level, one of the @c LOG_LEVEL_ values.
 * @param src_filename Source file path.
 * @param src_line_number Source line number.
 * @param fmt printf-style format.
 * @param ... Format arguments.
 */
void pbl_log_filtered_sync(uint8_t log_level, const char *src_filename, int src_line_number,
                           const char *fmt, ...) PBL_FORMAT_PRINTF(4, 5);

/**
 * @brief Format a message as a binary log record.
 *
 * The record holds a timestamp, the level, the line number, the last 15 characters of the file
 * name and the formatted message, truncated to fit.
 *
 * @param[out] buffer Destination, larger than the record header.
 * @param buffer_len Size of @p buffer in bytes.
 * @param log_level Level, one of the @c LOG_LEVEL_ values.
 * @param src_filename_path Source file path.
 * @param src_line_number Source line number.
 * @param fmt printf-style format.
 * @param args Format arguments.
 * @return Length of the record in bytes.
 */
int pbl_log_binary_format(char *buffer, int buffer_len, const uint8_t log_level,
                          const char *src_filename_path, int src_line_number, const char *fmt,
                          va_list args);

/**
 * @brief pbl_log_binary_format() with variadic arguments.
 *
 * @param[out] buffer Destination, larger than the record header.
 * @param buffer_len Size of @p buffer in bytes.
 * @param log_level Level, one of the @c LOG_LEVEL_ values.
 * @param src_filename_path Source file path.
 * @param src_line_number Source line number.
 * @param fmt printf-style format.
 * @param ... Format arguments.
 * @return Length of the record in bytes.
 */
int pbl_log_get_bin_format(char *buffer, int buffer_len, const uint8_t log_level,
                           const char *src_filename_path, int src_line_number, const char *fmt,
                           ...);

/** @brief Level of messages that are never filtered. */
#define LOG_LEVEL_ALWAYS 0
/** @brief Error level. */
#define LOG_LEVEL_ERROR 1
/** @brief Warning level. */
#define LOG_LEVEL_WARNING 50
/** @brief Info level. */
#define LOG_LEVEL_INFO 100
/** @brief Debug level. */
#define LOG_LEVEL_DEBUG 200
/** @brief Verbose debug level. */
#define LOG_LEVEL_DEBUG_VERBOSE 255

/** @brief Module level that disables every message of the module. */
#define LOG_LEVEL_OFF (-1)

/**
 * @def DEFAULT_LOG_LEVEL
 * @brief Compile-time level of files without a log module, from @c CONFIG_DEFAULT_LOG_LEVEL.
 */
#ifdef CONFIG_DEFAULT_LOG_LEVEL
#define DEFAULT_LOG_LEVEL CONFIG_DEFAULT_LOG_LEVEL
#else
#define DEFAULT_LOG_LEVEL LOG_LEVEL_DEBUG
#endif

/**
 * @def FLASH_LOG_LEVEL
 * @brief Highest level written to the flash log, from the @c CONFIG_FLASH_LOG_LEVEL_ choice.
 */
#if defined(CONFIG_FLASH_LOG_LEVEL_ERROR)
#define FLASH_LOG_LEVEL LOG_LEVEL_ERROR
#elif defined(CONFIG_FLASH_LOG_LEVEL_WARNING)
#define FLASH_LOG_LEVEL LOG_LEVEL_WARNING
#elif defined(CONFIG_FLASH_LOG_LEVEL_DEBUG)
#define FLASH_LOG_LEVEL LOG_LEVEL_DEBUG
#elif defined(CONFIG_FLASH_LOG_LEVEL_DEBUG_VERBOSE)
#define FLASH_LOG_LEVEL LOG_LEVEL_DEBUG_VERBOSE
#else
#define FLASH_LOG_LEVEL LOG_LEVEL_INFO
#endif

#ifdef CONFIG_LOG_HASHED
#include <pbl/logging/log_hashing.h>
#endif

/**
 * @name Log colors
 * Color names stored with hashed messages, used by the host console.
 * @{
 */
/** @brief Black, hardly readable. */
#define LOG_COLOR_BLACK "BLACK" // Not so useful in general
/** @brief Red. */
#define LOG_COLOR_RED "RED"
/** @brief Green. */
#define LOG_COLOR_GREEN "GREEN"
/** @brief Yellow. */
#define LOG_COLOR_YELLOW "YELLOW"
/** @brief Blue. */
#define LOG_COLOR_BLUE "BLUE"
/** @brief Magenta. */
#define LOG_COLOR_MAGENTA "MAGENTA"
/** @brief Cyan. */
#define LOG_COLOR_CYAN "CYAN"
/** @brief Grey. */
#define LOG_COLOR_GREY "GREY"
/** @brief Light grey, reserved for bold like the other light colors. Use sparingly. */
#define LOG_COLOR_LIGHT_GREY "LIGHT_GREY"
/** @brief Light red. */
#define LOG_COLOR_LIGHT_RED "LIGHT_RED"
/** @brief Light green. */
#define LOG_COLOR_LIGHT_GREEN "LIGHT_GREEN"
/** @brief Light yellow. */
#define LOG_COLOR_LIGHT_YELLOW "LIGHT_YELLOW"
/** @brief Light blue. */
#define LOG_COLOR_LIGHT_BLUE "LIGHT_BLUE"
/** @brief Light magenta. */
#define LOG_COLOR_LIGHT_MAGENTA "LIGHT_MAGENTA"
/** @brief Light cyan. */
#define LOG_COLOR_LIGHT_CYAN "LIGHT_CYAN"
/** @brief White. */
#define LOG_COLOR_WHITE "WHITE"

/** @brief Color of @ref LOG_LEVEL_ALWAYS messages. */
#define LOG_COLOR_FOR_ALWAYS LOG_COLOR_BLUE
/** @brief Color of @ref LOG_LEVEL_ERROR messages. */
#define LOG_COLOR_FOR_ERROR LOG_COLOR_RED
/** @brief Color of @ref LOG_LEVEL_WARNING messages. */
#define LOG_COLOR_FOR_WARNING LOG_COLOR_YELLOW
/** @brief Color of @ref LOG_LEVEL_INFO messages. */
#define LOG_COLOR_FOR_INFO LOG_COLOR_GREEN
/** @brief Color of @ref LOG_LEVEL_DEBUG messages. */
#define LOG_COLOR_FOR_DEBUG LOG_COLOR_GREY
/** @brief Color of @ref LOG_LEVEL_DEBUG_VERBOSE messages. */
#define LOG_COLOR_FOR_VERBOSE LOG_COLOR_GREY
/** @} */

#ifndef STRINGIFY
/**
 * @brief Turn the argument into a string literal without expanding it.
 *
 * @param a Argument.
 */
#define STRINGIFY_NX(a) #a
/**
 * @brief Turn the expansion of the argument into a string literal.
 *
 * @param a Argument.
 */
#define STRINGIFY(a) STRINGIFY_NX(a)
#endif // STRINGIFY

/**
 * @brief Turn the expansion of a status code into a string literal.
 *
 * @param s Status code.
 */
#define STATUS_STRING(s) STRINGIFY(s)

/** @cond INTERNAL_HIDDEN */
// Per-module compile-time log level and name. PBL_LOG_MODULE_DEFINE /
// PBL_LOG_MODULE_DECLARE override these tentative definitions, e.g.
// PBL_LOG_MODULE_DEFINE(service_activity, CONFIG_SERVICE_ACTIVITY_LOG_LEVEL) (see
// Kconfig.template.log_level). Kconfig never yields LOG_LEVEL_ALWAYS (0) for a
// module, so 0 marks a file without one; those use DEFAULT_LOG_LEVEL.
[[maybe_unused]] static const int16_t _pbl_log_module_level;
[[maybe_unused]] static const char *const _pbl_log_module_name;
// Runtime level of modules with CONFIG_<module>_LOG_LEVEL_RUNTIME, NULL otherwise.
[[maybe_unused]] static int16_t *const _pbl_log_module_runtime_level;

#define _PBL_LOG_PLACEHOLDER_1            0,
#define _PBL_LOG_IS_ENABLED(cfg)          _PBL_LOG_IS_ENABLED1(cfg)
#define _PBL_LOG_IS_ENABLED1(val)         _PBL_LOG_IS_ENABLED2(_PBL_LOG_PLACEHOLDER_##val)
#define _PBL_LOG_IS_ENABLED2(arg)         _PBL_LOG_IS_ENABLED3(arg 1, 0)
#define _PBL_LOG_IS_ENABLED3(_, val, ...) val

#define _PBL_LOG_CAT(a, b)  _PBL_LOG_CAT_(a, b)
#define _PBL_LOG_CAT_(a, b) a##b

#ifdef CONFIG_LOG_HASHED
// The MODULE map entry gives the loghash dict generator the
// file -> module mapping; the module name costs nothing at runtime.
#define _PBL_LOG_MODULE_STATIC(name, level)                                                   \
  [[maybe_unused]] static const int16_t _pbl_log_module_level = (level);                      \
  [[maybe_unused]] static const char *const _pbl_log_module_name = #name;                     \
  PBL_USED PBL_NOCOMMON PBL_SECTION(".log_strings") static const char _pbl_log_module_map[] = \
      "MODULE:" __FILE__ ":" #name
#else
#define _PBL_LOG_MODULE_STATIC(name, level)                              \
  [[maybe_unused]] static const int16_t _pbl_log_module_level = (level); \
  [[maybe_unused]] static const char *const _pbl_log_module_name = #name
#endif

// Runtime modules keep every message and filter on a shared level variable,
// initialized to the configured level.
#define _PBL_LOG_MODULE_DEFINE_0(name, level) _PBL_LOG_MODULE_STATIC(name, level)
#define _PBL_LOG_MODULE_DEFINE_1(name, level)      \
  int16_t _pbl_log_runtime_level_##name = (level); \
  _PBL_LOG_MODULE_DECLARE_1(name, level)

#define _PBL_LOG_MODULE_DECLARE_0(name, level) _PBL_LOG_MODULE_STATIC(name, level)
#define _PBL_LOG_MODULE_DECLARE_1(name, level)                           \
  extern int16_t _pbl_log_runtime_level_##name;                          \
  [[maybe_unused]] static int16_t *const _pbl_log_module_runtime_level = \
      &_pbl_log_runtime_level_##name;                                    \
  _PBL_LOG_MODULE_STATIC(name, LOG_LEVEL_DEBUG_VERBOSE)
/** @endcond */

/**
 * @def PBL_LOG_MODULE_DEFINE
 * @brief Put the current file in a log module, defining the module.
 *
 * Use it once per module, in one source file, before any PBL_LOG macro.
 *
 * @param name Module name, an identifier.
 * @param level Kconfig level symbol, @c CONFIG_<module>_LOG_LEVEL.
 */
/**
 * @def PBL_LOG_MODULE_DECLARE
 * @brief Put the current file in a log module defined in another file.
 *
 * @param name Module name, as given to PBL_LOG_MODULE_DEFINE().
 * @param level Kconfig level symbol, as given to PBL_LOG_MODULE_DEFINE().
 */
// Unit tests build with CONFIG_LOG but without the board Kconfig symbols,
// so module levels fall back to the default there.
#if defined(CONFIG_LOG) && !defined(UNITTEST)
#define PBL_LOG_MODULE_DEFINE(name, level) \
  _PBL_LOG_CAT(_PBL_LOG_MODULE_DEFINE_, _PBL_LOG_IS_ENABLED(level##_RUNTIME))(name, level)
#define PBL_LOG_MODULE_DECLARE(name, level) \
  _PBL_LOG_CAT(_PBL_LOG_MODULE_DECLARE_, _PBL_LOG_IS_ENABLED(level##_RUNTIME))(name, level)
/** @cond INTERNAL_HIDDEN */
#define _PBL_LOG_FN(fn, filtered_fn) (_pbl_log_module_runtime_level != NULL ? filtered_fn : fn)
/** @endcond */
#else
#define PBL_LOG_MODULE_DEFINE(name, level) \
  [[maybe_unused]] static const int16_t _pbl_log_module_level = 0
#define PBL_LOG_MODULE_DECLARE(name, level) PBL_LOG_MODULE_DEFINE(name, level)
/** @cond INTERNAL_HIDDEN */
// Host builds may not fold the selection and lack the filtered functions.
#define _PBL_LOG_FN(fn, filtered_fn)        fn
/** @endcond */
#endif

/**
 * @brief Get the runtime level of a module built with @c CONFIG_<module>_LOG_LEVEL_RUNTIME.
 *
 * @param name Module name.
 * @return Current level.
 */
#define PBL_LOG_MODULE_LEVEL_GET(name)                                 \
  ({                                                                   \
    extern int16_t _pbl_log_runtime_level_##name;                      \
    __atomic_load_n(&_pbl_log_runtime_level_##name, __ATOMIC_RELAXED); \
  })
/**
 * @brief Set the runtime level of a module built with @c CONFIG_<module>_LOG_LEVEL_RUNTIME.
 *
 * Messages above the level are dropped; the global sink levels no longer apply to the module.
 *
 * @param name Module name.
 * @param level New level, one of the @c LOG_LEVEL_ values.
 */
#define PBL_LOG_MODULE_LEVEL_SET(name, level)                                    \
  do {                                                                           \
    extern int16_t _pbl_log_runtime_level_##name;                                \
    __atomic_store_n(&_pbl_log_runtime_level_##name, (level), __ATOMIC_RELAXED); \
  } while (0)

/**
 * @brief Check whether the current file logs messages of a level.
 *
 * Applies the module (or default) compile-time level and the module runtime level, if any.
 *
 * @param level Level, one of the @c LOG_LEVEL_ values.
 */
#define PBL_SHOULD_LOG(level)                                                             \
  ((level) <= (_pbl_log_module_level != 0 ? _pbl_log_module_level : DEFAULT_LOG_LEVEL) && \
   (_pbl_log_module_runtime_level == NULL ||                                              \
    (level) <= __atomic_load_n(_pbl_log_module_runtime_level, __ATOMIC_RELAXED)))

/**
 * @def PBL_LOG_COLOR
 * @brief Log a message with an explicit level and color, possibly queued.
 *
 * Prefer the level-named macros.
 *
 * @param level Level, one of the @c LOG_LEVEL_ values.
 * @param color Color, one of the @c LOG_COLOR_ values.
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
/**
 * @def PBL_LOG_COLOR_SYNC
 * @brief Log a message with an explicit level and color, sent before returning.
 *
 * Prefer the level-named macros.
 *
 * @param level Level, one of the @c LOG_LEVEL_ values.
 * @param color Color, one of the @c LOG_COLOR_ values.
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
// Internal implementation macros (use level-named macros below instead)

#ifdef CONFIG_LOG
#ifdef CONFIG_LOG_HASHED
#define PBL_LOG_COLOR(level, color, fmt, ...)                                                      \
  do {                                                                                             \
    if (PBL_SHOULD_LOG(level)) {                                                                   \
      NEW_LOG_HASH(_PBL_LOG_FN(pbl_log_hashed_async, pbl_log_hashed_filtered_async), level, color, \
                   fmt, ##__VA_ARGS__);                                                            \
    }                                                                                              \
  } while (0)

#define PBL_LOG_COLOR_SYNC(level, color, fmt, ...)                                               \
  do {                                                                                           \
    if (PBL_SHOULD_LOG(level)) {                                                                 \
      NEW_LOG_HASH(_PBL_LOG_FN(pbl_log_hashed_sync, pbl_log_hashed_filtered_sync), level, color, \
                   fmt, ##__VA_ARGS__);                                                          \
    }                                                                                            \
  } while (0)
#else
#define PBL_LOG_COLOR(level, color, fmt, ...)                                         \
  do {                                                                                \
    if (PBL_SHOULD_LOG(level)) {                                                      \
      if (_pbl_log_module_name != NULL) {                                             \
        _PBL_LOG_FN(pbl_log, pbl_log_filtered)(level, __FILE__, __LINE__, "%s: " fmt, \
                                               _pbl_log_module_name, ##__VA_ARGS__);  \
      } else {                                                                        \
        pbl_log(level, __FILE__, __LINE__, fmt, ##__VA_ARGS__);                       \
      }                                                                               \
    }                                                                                 \
  } while (0)

#define PBL_LOG_COLOR_SYNC(level, color, fmt, ...)                                              \
  do {                                                                                          \
    if (PBL_SHOULD_LOG(level)) {                                                                \
      if (_pbl_log_module_name != NULL) {                                                       \
        _PBL_LOG_FN(pbl_log_sync, pbl_log_filtered_sync)(level, __FILE__, __LINE__, "%s: " fmt, \
                                                         _pbl_log_module_name, ##__VA_ARGS__);  \
      } else {                                                                                  \
        pbl_log_sync(level, __FILE__, __LINE__, fmt, ##__VA_ARGS__);                            \
      }                                                                                         \
    }                                                                                           \
  } while (0)
#endif
#else // !CONFIG_LOG
#define PBL_LOG_COLOR(level, color, fmt, ...)
#define PBL_LOG_COLOR_SYNC(level, color, fmt, ...)
#endif // CONFIG_LOG

// Level-named macros (async)
/**
 * @brief Log a message that is never filtered, possibly queued.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_ALWAYS(fmt, ...) \
  PBL_LOG_COLOR(LOG_LEVEL_ALWAYS, LOG_COLOR_FOR_ALWAYS, fmt, ##__VA_ARGS__)
/**
 * @brief Log an error, possibly queued.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_ERR(fmt, ...) \
  PBL_LOG_COLOR(LOG_LEVEL_ERROR, LOG_COLOR_FOR_ERROR, fmt, ##__VA_ARGS__)
/**
 * @brief Log a warning, possibly queued.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_WRN(fmt, ...) \
  PBL_LOG_COLOR(LOG_LEVEL_WARNING, LOG_COLOR_FOR_WARNING, fmt, ##__VA_ARGS__)
/**
 * @brief Log an attention-worthy event, possibly queued.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_INFO(fmt, ...) PBL_LOG_COLOR(LOG_LEVEL_INFO, LOG_COLOR_FOR_INFO, fmt, ##__VA_ARGS__)
/**
 * @brief Log a routine debug message, possibly queued.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_DBG(fmt, ...) \
  PBL_LOG_COLOR(LOG_LEVEL_DEBUG, LOG_COLOR_FOR_DEBUG, fmt, ##__VA_ARGS__)
/**
 * @brief Log a verbose debug message, possibly queued.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_VERBOSE(fmt, ...) \
  PBL_LOG_COLOR(LOG_LEVEL_DEBUG_VERBOSE, LOG_COLOR_FOR_VERBOSE, fmt, ##__VA_ARGS__)

// Level-named sync macros
/**
 * @brief Log a message that is never filtered, sent before returning.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_SYNC_ALWAYS(fmt, ...) \
  PBL_LOG_COLOR_SYNC(LOG_LEVEL_ALWAYS, LOG_COLOR_FOR_ALWAYS, fmt, ##__VA_ARGS__)
/**
 * @brief Log an error, sent before returning.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_SYNC_ERR(fmt, ...) \
  PBL_LOG_COLOR_SYNC(LOG_LEVEL_ERROR, LOG_COLOR_FOR_ERROR, fmt, ##__VA_ARGS__)
/**
 * @brief Log a warning, sent before returning.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_SYNC_WRN(fmt, ...) \
  PBL_LOG_COLOR_SYNC(LOG_LEVEL_WARNING, LOG_COLOR_FOR_WARNING, fmt, ##__VA_ARGS__)
/**
 * @brief Log an attention-worthy event, sent before returning.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_SYNC_INFO(fmt, ...) \
  PBL_LOG_COLOR_SYNC(LOG_LEVEL_INFO, LOG_COLOR_FOR_INFO, fmt, ##__VA_ARGS__)
/**
 * @brief Log a routine debug message, sent before returning.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_SYNC_DBG(fmt, ...) \
  PBL_LOG_COLOR_SYNC(LOG_LEVEL_DEBUG, LOG_COLOR_FOR_DEBUG, fmt, ##__VA_ARGS__)
/**
 * @brief Log a verbose debug message, sent before returning.
 *
 * @param fmt printf-style format, a string literal.
 * @param ... Format arguments.
 */
#define PBL_LOG_SYNC_VERBOSE(fmt, ...) \
  PBL_LOG_COLOR_SYNC(LOG_LEVEL_DEBUG_VERBOSE, LOG_COLOR_FOR_VERBOSE, fmt, ##__VA_ARGS__)

/**
 * @def RETURN_STATUS
 * @brief Return a status code, logging a warning if it is a failure.
 *
 * @param st Status code.
 */
/**
 * @def RETURN_STATUS_UP
 * @brief Return a status code to the caller, turning @c E_INVALID_ARGUMENT into @c E_INTERNAL.
 *
 * An invalid argument passed down by this layer is an internal error for its caller.
 *
 * @param st Status code.
 */
#ifdef CONFIG_LOG
#define RETURN_STATUS(st)           \
  do {                              \
    if (FAILED(st)) {               \
      PBL_LOG_WRN("%d", (int)(st)); \
    }                               \
    return st;                      \
  } while (0)

#define RETURN_STATUS_UP(st) return ((st) != E_INVALID_ARGUMENT ? (st) : E_INTERNAL)
#else // CONFIG_LOG
#define RETURN_STATUS(st)    return (st)
#define RETURN_STATUS_UP(st) return ((st) == E_INVALID_ARGUMENT ? E_INTERNAL : (st))
#endif // CONFIG_LOG

/** @} */
