# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

"""Kconfig-driven C library selection.

Picks the C library the firmware links against (see lib/c/Kconfig) and
exposes the choice to the link step via three env vars, consumed by
_link_firmware in the top-level wscript:

  LIBC_LINKFLAGS  extra link flags (-nostartfiles / -specs=...)
  LIBC_LIBS       libraries passed to bld.program(lib=...)
  LIBC_USE        extra use= targets (_sbrk, the assert hook, the nano
                  printf shim)

Compile/link also gain the flags that make the toolchain libc match the
firmware's expectations (32-bit time_t, the integer printf aliases).
picolibc is taken pre-built from the toolchain
when available (the PebbleOS SDK ships one built with the firmware ABI),
otherwise built from the third_party/picolibc submodule. Runs at
configure time, after pebble_arm_gcc has set the architecture flags.
"""

import os
import subprocess

from waflib import Errors, Logs

# newlib defaults time_t to 64-bit; keep it 32-bit (long) to match the
# firmware's RTC/storage and %ld format strings.
_NEWLIB_TIME_DEFINE = "-D_USE_LONG_TIME_T"

# The firmware calls the integer-only printf names; map them to the real
# ones (the historical in-tree libc aliased them in its headers).
_SNIPRINTF_DEFINES = ["-Dsniprintf=snprintf", "-Dvsniprintf=vsnprintf"]

# The firmware compiles with -std=c11 (strict ANSI), but it uses POSIX/BSD
# names (strnlen, strcasecmp, ...) that the toolchain libcs hide behind
# feature-test macros under __STRICT_ANSI__; ask for the default surface
# explicitly.
_DEFAULT_SOURCE_DEFINE = "-D_DEFAULT_SOURCE"

_ARCH_PREFIXES = ("-mthumb", "-mcpu=", "-mfloat-abi=", "-mfpu=", "-march=")

# picolibc build options: single arch, no crt0/semihosting (the firmware
# supplies its own startup and syscalls), C99 + long-long formatted I/O,
# and a single global TLS block (per-task TLS is a separate integration).
_PICOLIBC_MESON_OPTS = [
    "-Dmultilib=false",
    "-Dpicocrt=false",
    "-Dsemihost=false",
    "-Dtests=false",
    "-Dio-long-long=true",
    "-Dformat-default=long-long",
    "-Dthread-local-storage=false",
]


def _add(conf, flags):
    conf.env.append_value("CFLAGS", flags)
    conf.env.append_value("LINKFLAGS", flags)


def _select_newlib(conf, nano):
    conf.env.LIBC_LINKFLAGS = ["-nostartfiles", "-specs=nosys.specs"]
    if nano:
        conf.env.LIBC_LINKFLAGS.insert(1, "-specs=nano.specs")
    conf.env.LIBC_LIBS = ["m", "gcc"]
    conf.env.LIBC_USE = ["libc_syscalls"]
    if nano:
        # nano's printf lacks C99 length modifiers; link our shim ahead.
        conf.env.LIBC_USE.append("libc_printf")
    _add(conf, [_NEWLIB_TIME_DEFINE, _DEFAULT_SOURCE_DEFINE] + _SNIPRINTF_DEFINES)


def _arch_flags(conf):
    return [f for f in conf.env.CFLAGS if any(f.startswith(p) for p in _ARCH_PREFIXES)]


def _picolibc_time_override(conf, out):
    """picolibc hardcodes 64-bit __time_t. The firmware wants 32-bit (to
    match its RTC/storage and %ld formats), so force-include a machine
    override into *both* the picolibc build and the firmware, keeping the
    ABI of time_t-taking functions (mktime/localtime/...) consistent."""
    hdr = out.make_node("picolibc_machine_override.h")
    hdr.write(
        "/* Generated by tools/waf/libc.py. */\n"
        "#ifndef _PBL_PICOLIBC_MACHINE_OVERRIDE_H\n"
        "#define _PBL_PICOLIBC_MACHINE_OVERRIDE_H\n"
        "/* picolibc force-includes this into .S files too; C-only. */\n"
        "#ifndef __ASSEMBLER__\n"
        "typedef long __time_t;\n"
        "#define __machine_time_t_defined\n"
        "#endif\n"
        "#endif\n"
    )
    return hdr.abspath()


def _build_picolibc(conf):
    """Build third_party/picolibc for the current arch; return specs path."""
    src = conf.srcnode.find_node("third_party/picolibc")
    if src is None or src.find_node("meson.build") is None:
        conf.fatal(
            "third_party/picolibc submodule missing; run "
            "`git submodule update --init third_party/picolibc`"
        )
    meson = conf.find_program("meson", var="MESON", mandatory=True)[0]
    ninja = conf.find_program("ninja", var="NINJA", mandatory=True)[0]

    out = conf.bldnode.make_node("picolibc")
    out.mkdir()
    builddir = out.make_node("build")
    install = out.make_node("install")
    override = _picolibc_time_override(conf, out)
    arch = _arch_flags(conf) + ["-include", override]
    arch_lit = ", ".join(f"'{a}'" for a in arch)

    out.make_node("cross.txt").write(
        "[binaries]\n"
        f"c = ['arm-none-eabi-gcc', {arch_lit}, '-nostdlib']\n"
        f"cpp = ['arm-none-eabi-g++', {arch_lit}, '-nostdlib']\n"
        "ar = 'arm-none-eabi-ar'\nas = 'arm-none-eabi-as'\n"
        "nm = 'arm-none-eabi-nm'\nstrip = 'arm-none-eabi-strip'\n"
        "[host_machine]\n"
        "system = 'none'\ncpu_family = 'arm'\ncpu = 'arm'\nendian = 'little'\n"
        "[properties]\nskip_sanity_check = true\n"
    )

    if not builddir.find_node("build.ninja"):
        conf.start_msg("Configuring picolibc")
        subprocess.check_call(
            [
                meson,
                "setup",
                builddir.abspath(),
                src.abspath(),
                "--cross-file",
                out.make_node("cross.txt").abspath(),
                "-Dspecsdir=" + install.make_node("lib").abspath(),
                "--prefix=" + install.abspath(),
            ]
            + _PICOLIBC_MESON_OPTS
        )
        conf.end_msg("done")
    conf.start_msg("Building picolibc")
    subprocess.check_call([ninja, "-C", builddir.abspath(), "install"])
    conf.end_msg("done")

    specs = install.find_node("lib/picolibc.specs")
    if specs is None:
        conf.fatal("picolibc build did not produce picolibc.specs")
    # The firmware needs the same 32-bit time_t override picolibc built with.
    _add(conf, ["-include", override])
    return specs.abspath()


def _find_prebuilt_picolibc(conf):
    cc = conf.env.CC[-1] if isinstance(conf.env.CC, list) else conf.env.CC
    try:
        out = conf.cmd_and_log([cc, "-print-file-name=picolibc.specs"]).strip()
    except Errors.WafError:
        out = "picolibc.specs"
    # gcc echoes the name back unchanged when it can't find the file.
    if out and out != "picolibc.specs" and os.path.isfile(out):
        return out
    return None


def _select_picolibc(conf):
    prebuilt = None
    if not conf.env.CONFIG_LIBC_PICOLIBC_FROM_SOURCE:
        prebuilt = _find_prebuilt_picolibc(conf)
        if prebuilt is None:
            Logs.warn(
                "WARNING: no pre-built picolibc in the toolchain (not using "
                "the PebbleOS SDK toolchain?); building picolibc from source "
                "(third_party/picolibc)."
            )
    specs = prebuilt or _build_picolibc(conf)
    conf.env.LIBC_LINKFLAGS = ["-nostartfiles"]
    conf.env.LIBC_LIBS = ["m", "gcc"]
    conf.env.LIBC_USE = ["libc_syscalls"]
    # picolibc.specs supplies headers (cpp -isystem) and the libc link, so
    # it must be on both the compile and link lines.
    _add(conf, ["-specs=" + specs, _DEFAULT_SOURCE_DEFINE] + _SNIPRINTF_DEFINES)
    return "pre-built" if prebuilt else "from source"


def configure(conf):
    if conf.env.CONFIG_LIBC_NEWLIB or conf.env.CONFIG_LIBC_NEWLIB_NANO:
        nano = bool(conf.env.CONFIG_LIBC_NEWLIB_NANO)
        _select_newlib(conf, nano)
        conf.msg("libc", "newlib-nano" if nano else "newlib")
    elif conf.env.CONFIG_LIBC_PICOLIBC:
        origin = _select_picolibc(conf)
        conf.msg("libc", f"picolibc ({origin})")
    else:
        conf.fatal("No C library selected (see lib/c/Kconfig)")

    # __assert_func override (lib/c/assert.c): routes the newlib-family
    # assert() through PBL_LOG/PBL_ASSERT for every libc selection.
    conf.env.append_value("LIBC_USE", ["libc_assert"])
