# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

pbl_libs += [
  {
    'name': 'watch_app_kickstart',
    'srcs': files('kickstart/kickstart.c'),
    'inc': ['.'],
  },
]
subdir('tictoc')
pbl_libs += [
  {
    'name': 'watch_app_low_power',
    'srcs': files('low_power/face.c'),
    'inc': ['.'],
  },
]
