#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

"""Run Kconfig for a board and export the result to CMake.

Writes ``.config`` and ``autoconf.h`` into the build directory, plus a
``config.cmake`` that sets one CMake variable per symbol and lists the
Kconfig sources the configuration depends on.
"""

import argparse
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO_ROOT)

import kconfiglib

from tools import boards


def parse_override(override):
    if "=" not in override:
        sys.exit(f"Invalid Kconfig override '{override}': expected CONFIG_FOO=value")
    key, value = override.split("=", 1)
    if not key.startswith("CONFIG_"):
        sys.exit(
            f"Invalid Kconfig override '{override}': symbol name must look like CONFIG_FOO"
        )
    return key[len("CONFIG_") :], value


def check_assigned_values(kconf):
    """Warn about assignments overridden by unsatisfied dependencies, the
    same way Zephyr's check_assigned_sym_values() does."""
    for sym in kconf.unique_defined_syms:
        if sym.choice or sym.user_value is None:
            continue

        if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
            user_str = kconfiglib.TRI_TO_STR[sym.user_value]
        else:
            user_str = sym.user_value

        if user_str == sym.str_value:
            continue

        deps = kconfiglib.split_expr(sym.direct_dep, kconfiglib.AND)
        if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
            mdeps = [d for d in deps if kconfiglib.expr_value(d) < sym.user_value]
        else:
            mdeps = [d for d in deps if kconfiglib.expr_value(d) == 0]
        dep_strs = [
            f"{kconfiglib.expr_str(d)} "
            f"(={kconfiglib.TRI_TO_STR[kconfiglib.expr_value(d)]})"
            for d in mdeps
        ]
        kconf.warnings.append(
            f"CONFIG_{sym.name}={user_str} was resolved to {sym.str_value}. "
            f"Check these unsatisfied dependencies: {', '.join(dep_strs)}"
        )


def cmake_escape(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


def write_config_cmake(path, kconf, board, deps):
    lines = [
        "# Generated by tools/cmake/kconfig.py -- do not edit.\n",
        f'set(PBL_BOARD "{board.target}")\n',
        f'set(PBL_BOARD_NAME "{board.name}")\n',
        f'set(PBL_BOARD_REVISION "{board.revision or ""}")\n',
        f'set(PBL_BOARD_NORMALIZED "{board.normalized}")\n',
        'set(PBL_BOARD_RUNNERS "{}")\n'.format(";".join(board.runners)),
    ]
    for sym in kconf.unique_defined_syms:
        if not sym.nodes:
            continue
        value = sym.str_value
        if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
            if value == "n":
                continue
        elif sym.type == kconfiglib.STRING:
            pass
        elif value == "":
            continue
        lines.append(f'set(CONFIG_{sym.name} "{cmake_escape(value)}")\n')
    lines.append("set(PBL_KCONFIG_DEPENDS\n")
    lines.extend(f'  "{cmake_escape(dep)}"\n' for dep in deps)
    lines.append(")\n")
    with open(path, "w") as f:
        f.writelines(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--srcdir", required=True)
    parser.add_argument("--builddir", required=True)
    parser.add_argument("--board", required=True)
    parser.add_argument("--variant", default="normal")
    parser.add_argument("--override", action="append", default=[])
    parser.add_argument("--fragment", help="extra .conf applied last")
    args = parser.parse_args()

    srcdir = os.path.abspath(args.srcdir)
    builddir = os.path.abspath(args.builddir)

    try:
        board = boards.parse_board(srcdir, args.board)
    except (TypeError, ValueError) as e:
        sys.exit(str(e))

    defconfig = os.path.join(srcdir, "boards", board.name, "defconfig")
    if not os.path.exists(defconfig):
        sys.exit(f"Board defconfig not found: {defconfig}")

    os.environ["srctree"] = srcdir
    # The board is known from BOARD; export it so the root Kconfig can source
    # only the active board's Kconfig via `rsource "boards/$(BOARD)/..."`.
    os.environ["BOARD"] = board.name
    os.environ["BOARD_REVISION"] = board.revision or boards.NO_REVISION

    kconf = kconfiglib.Kconfig(os.path.join(srcdir, "Kconfig"))
    kconf.warn_assign_override = True
    kconf.warn_assign_redun = True
    kconf.warn_assign_undef = True

    sources = [defconfig]
    kconf.load_config(defconfig)

    revision_defconfig = os.path.join(
        srcdir, "boards", board.name, f"defconfig.{board.revision}"
    )
    if board.revision and os.path.exists(revision_defconfig):
        kconf.load_config(revision_defconfig, replace=False)
        sources.append(revision_defconfig)

    prj_conf = os.path.join(srcdir, "src", "fw", "prj.conf")
    if os.path.exists(prj_conf):
        kconf.load_config(prj_conf, replace=False)
        sources.append(prj_conf)

    variant_conf = os.path.join(srcdir, "src", "fw", f"prj_{args.variant}.conf")
    if os.path.exists(variant_conf):
        kconf.load_config(variant_conf, replace=False)
        sources.append(variant_conf)

    # An interactively edited configuration, kept across reconfigurations.
    if args.fragment and os.path.exists(args.fragment):
        kconf.load_config(args.fragment, replace=False)
        sources.append(args.fragment)

    for override in args.override:
        name, value = parse_override(override)
        sym = kconf.syms.get(name)
        if sym is None or not sym.nodes:
            sys.exit(f"Undefined Kconfig symbol in override: CONFIG_{name}")
        sym.set_value(value)

    check_assigned_values(kconf)

    if kconf.warnings:
        for warning in kconf.warnings:
            print(f"Kconfig: {warning}", file=sys.stderr)
        sys.exit("Kconfig warnings found, aborting")

    os.makedirs(builddir, exist_ok=True)
    kconf.write_config(os.path.join(builddir, ".config"))
    kconf.write_autoconf(os.path.join(builddir, "autoconf.h"))

    deps = sources + [
        os.path.join(srcdir, name) if not os.path.isabs(name) else name
        for name in kconf.kconfig_filenames
    ]
    write_config_cmake(os.path.join(builddir, "config.cmake"), kconf, board, deps)

    summary = f"{len(kconf.unique_defined_syms)} symbols for {board.target}"
    if args.override:
        summary += f" + {len(args.override)} override(s)"
    print(summary)


if __name__ == "__main__":
    main()
