# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

add_subdirectory(base)
pbl_add_subdirectory_ifdef(CONFIG_SPEAKER speaker)
pbl_add_subdirectory_ifdef(CONFIG_AMBIENT_LIGHT ambient)
pbl_add_subdirectory_ifdef(CONFIG_TEMPERATURE temperature)
pbl_add_subdirectory_ifdef(CONFIG_BATTERY battery)
add_subdirectory(button)
add_subdirectory(crc)
add_subdirectory(imu)
pbl_add_subdirectory_ifdef(CONFIG_DISPLAY display)
pbl_add_subdirectory_ifdef(CONFIG_EXTI exti)
pbl_add_subdirectory_ifdef(CONFIG_FLASH flash)
pbl_add_subdirectory_ifdef(CONFIG_GPIO gpio)
pbl_add_subdirectory_ifdef(CONFIG_I2C i2c)
add_subdirectory(mcu)
pbl_add_subdirectory_ifdef(CONFIG_BACKLIGHT backlight)
pbl_add_subdirectory_ifdef(CONFIG_PRESSURE pressure)
pbl_add_subdirectory_ifdef(CONFIG_MIC mic)
pbl_add_subdirectory_ifdef(CONFIG_OTP otp)
pbl_add_subdirectory_ifdef(CONFIG_PMIC pmic)
pbl_add_subdirectory_ifdef(CONFIG_PWM pwm)
pbl_add_subdirectory_ifdef(CONFIG_RNG rng)
pbl_add_subdirectory_ifdef(CONFIG_RTC rtc)
pbl_add_subdirectory_ifdef(CONFIG_TOUCH touch)
pbl_add_subdirectory_ifdef(CONFIG_UART uart)
pbl_add_subdirectory_ifdef(CONFIG_VIBE vibe)
pbl_add_subdirectory_ifdef(CONFIG_WATCHDOG watchdog)
pbl_add_subdirectory_ifdef(CONFIG_HRM hrm)
pbl_add_subdirectory_ifdef(CONFIG_SOC_NRF52 nrf5)
pbl_add_subdirectory_ifdef(CONFIG_SOC_SF32LB52 sf32lb52)
