# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

set(excludes)
if(NOT CONFIG_BT_GH3X2X_TUNING_SERVICE)
  list(APPEND excludes gh3x2x_tuning_service.c)
endif()
if(NOT CONFIG_BT_CONTROLLER_PROBE)
  list(APPEND excludes controller_probe.c)
endif()
if(NOT CONFIG_BT_CLASSIC)
  list(APPEND excludes nimble_classic.c)
endif()
file(GLOB sources CONFIGURE_DEPENDS *.c)
pbl_filter_sources(sources EXCLUDE ${excludes})
pbl_library()
pbl_library_sources(${sources})
if(CONFIG_BT_CLASSIC)
  pbl_library_include_directories(${PBL_BASE}/third_party/nimble/mynewt-nimble/nimble/host/src)
endif()

if(CONFIG_BT_HFP)
  add_subdirectory(classic)
endif()
if(CONFIG_BT_HCI_AUDIO_PROBE OR CONFIG_BT_HCI_AUDIO_ADAPTER)
  add_subdirectory(sf32lb52)
endif()
