# PebbleOS application-level Kconfig overrides.
# Values here are applied on top of the board defconfig and below variant-
# specific prj_<variant>.conf overrides.

# Subsystems.
CONFIG_CRON=y

# Common services.
CONFIG_SERVICE_ACCEL_MANAGER=y
CONFIG_SERVICE_ANALYTICS=y
CONFIG_SERVICE_ANIMATION_SERVICE=y
CONFIG_SERVICE_BATTERY=y
CONFIG_SERVICE_BLUETOOTH=y
CONFIG_SERVICE_BOOT_SPLASH=y
CONFIG_SERVICE_CLOCK=y
CONFIG_SERVICE_COMM_SESSION=y
CONFIG_SERVICE_COMPOSITOR=y
CONFIG_SERVICE_DEBOUNCED_CONNECTION_SERVICE=y
CONFIG_SERVICE_EVENT_SERVICE=y
CONFIG_SERVICE_EVENTED_TIMER=y
CONFIG_SERVICE_FIRMWARE_UPDATE=y
CONFIG_SERVICE_GET_BYTES=y
CONFIG_SERVICE_I18N=y
CONFIG_SERVICE_LIGHT=y
CONFIG_SERVICE_NEW_TIMER=y
CONFIG_SERVICE_PHONE_PP=y
CONFIG_SERVICE_PING=y
CONFIG_SERVICE_POLL_REMOTE=y
CONFIG_SERVICE_PRF_UPDATE=y
CONFIG_SERVICE_PUT_BYTES=y
CONFIG_SERVICE_REGISTRY_ENDPOINT=y
CONFIG_SERVICE_REGULAR_TIMER=y
CONFIG_SERVICE_SERVICES_COMMON=y
CONFIG_SERVICE_SHARED_PRF_STORAGE=y
CONFIG_SERVICE_SYSTEM_TASK=y
CONFIG_SERVICE_TICK_TIMER=y
CONFIG_SERVICE_VIBE_PATTERN=y
