/* SPDX-FileCopyrightText: 2026 Core Devices LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

#include <stdbool.h>
#include <stdint.h>

//! Battery state-of-charge estimator for a single Li-ion/Li-po cell.
//!
//! The cell is modelled as an open-circuit voltage source that depends on the
//! state of charge (SOC), in series with a resistor R0 and one R1||C1
//! polarization pair. An extended Kalman filter combines coulomb counting
//! (prediction) with the measured terminal voltage (correction). The library
//! has no OS dependencies. See docs/architecture/fuel_gauge.md for the model,
//! the tuning and how to fit a cell model with tools/fuel_gauge.py.
//!
//! Units are SI throughout: V, A, s, degrees Celsius, Ah. Current is positive
//! when the battery discharges.

//! A point of the open-circuit voltage curve.
struct pbl_fuel_gauge_ocv_point {
  //! State of charge, 0 (empty) to 1 (full).
  float soc;
  //! Open-circuit voltage at rest and 25 C [V].
  float v;
};

//! Cell model, normally generated by `tools/fuel_gauge.py fit`.
struct pbl_fuel_gauge_model {
  const char *name;
  //! Charge between the full and the empty point at 25 C [Ah].
  float capacity_ah;
  //! Strictly increasing in both SOC and voltage, from SOC 0 to SOC 1.
  const struct pbl_fuel_gauge_ocv_point *ocv;
  uint8_t ocv_count;
  //! Series resistance at 25 C [ohm].
  float r0;
  //! Polarization resistance at 25 C [ohm].
  float r1;
  //! Polarization time constant R1 * C1 [s].
  float tau1;
  //! Resistances scale by exp(r_temp_coeff * (25 - T)) [1/C].
  float r_temp_coeff;
};

//! Estimator configuration.
struct pbl_fuel_gauge_config {
  const struct pbl_fuel_gauge_model *model;
  //! Standard deviation of the voltage model and measurement error [V].
  float voltage_noise;
  //! Standard deviation of the error of a current sample as the average
  //! current over the time since the previous sample [A].
  float current_noise;
  //! Charger termination voltage [V], used for time-to-full.
  float term_voltage;
  //! Charger termination current [A], used for time-to-full.
  float term_current;
};

//! A battery measurement. Voltage and current should be sampled together.
struct pbl_fuel_gauge_meas {
  //! Terminal voltage [V].
  float v;
  //! Current, positive when discharging [A].
  float i;
  //! Cell temperature [C].
  float t;
};

enum pbl_fuel_gauge_charge_state {
  PBL_FUEL_GAUGE_DISCHARGING,
  //! Constant current, including trickle charge.
  PBL_FUEL_GAUGE_CHARGING_CC,
  PBL_FUEL_GAUGE_CHARGING_CV,
  //! The charger terminated: the battery is full.
  PBL_FUEL_GAUGE_CHARGE_COMPLETE,
};

//! Estimator state that survives a reboot, see pbl_fuel_gauge_state_get().
struct pbl_fuel_gauge_state {
  //! Checksum of the model and state layout the state was produced with.
  uint32_t model_id;
  //! Estimated SOC and polarization voltage.
  float soc;
  float v1;
  //! Estimate covariance: var(soc), cov(soc, v1), var(v1).
  float p_soc;
  float p_cross;
  float p_v1;
  //! Reported SOC, see pbl_fuel_gauge_update().
  float soc_reported;
  //! Exponentially weighted charge and time for the average current.
  float avg_charge;
  float avg_time;
};

//! Estimator instance, treat as opaque.
struct pbl_fuel_gauge {
  const struct pbl_fuel_gauge_config *config;
  struct pbl_fuel_gauge_state state;
  enum pbl_fuel_gauge_charge_state charge_state;
  struct pbl_fuel_gauge_meas last;
};

//! Initializes the estimator. Without @p saved, or when @p saved belongs to
//! another model or disagrees with the voltage by too much (another battery,
//! or a long time without power), the SOC starts from the open-circuit
//! voltage implied by @p meas.
//! @return 1 when @p saved was used, 0 when starting from the voltage,
//! -EINVAL for an invalid configuration.
int pbl_fuel_gauge_init(struct pbl_fuel_gauge *fg, const struct pbl_fuel_gauge_config *config,
                        const struct pbl_fuel_gauge_meas *meas,
                        const struct pbl_fuel_gauge_state *saved);

//! Processes a measurement taken @p dt seconds after the previous one.
//! @return the reported SOC [%]. Once the estimate has settled, it does not
//! rise while discharging nor drop while charging, so corrections from the
//! voltage are only shown when they move in the direction the battery is
//! going.
float pbl_fuel_gauge_update(struct pbl_fuel_gauge *fg, const struct pbl_fuel_gauge_meas *meas,
                            float dt, enum pbl_fuel_gauge_charge_state charge_state);

//! @return the estimated SOC, 0 to 1, without the reporting constraints.
float pbl_fuel_gauge_soc_get(const struct pbl_fuel_gauge *fg);

//! @param[out] seconds time until empty at the average discharge current.
//! @return false while charging or while the average is not settled yet.
bool pbl_fuel_gauge_tte_get(const struct pbl_fuel_gauge *fg, uint32_t *seconds);

//! @param[out] seconds time until the charger terminates.
//! @return false when not charging or not settled yet.
bool pbl_fuel_gauge_ttf_get(const struct pbl_fuel_gauge *fg, uint32_t *seconds);

void pbl_fuel_gauge_state_get(const struct pbl_fuel_gauge *fg, struct pbl_fuel_gauge_state *state);
