# SPDX-FileCopyrightText: 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0

"""Resource build steps, independent of any build system.

Each function takes plain paths and data and writes one build artifact.
The waf task classes in ``waftools/`` and the CMake driver in
``tools/meson/resources.py`` are thin wrappers around these.
"""

import generate_c_byte_array
from pbpack import ResourcePack
from resources.types.resource_ball import ResourceBall
from resources.types.resource_definition import ResourceDefinition, StorageType
from resources.types.resource_object import ResourceObject

ENUM_HEADER = """#pragma once

//
// AUTOGENERATED BY BUILD
// DO NOT MODIFY - CHANGES WILL BE OVERWRITTEN
//

typedef enum {
  INVALID_RESOURCE = 0,
  RESOURCE_ID_INVALID = 0,
  DEFAULT_MENU_ICON = 0,
"""

DEFINE_HEADER = """#pragma once

//
// AUTOGENERATED BY BUILD
// DO NOT MODIFY - CHANGES WILL BE OVERWRITTEN
//

#define  DEFAULT_MENU_ICON  0

"""

EXTERN_HEADER = """#pragma once
#include <stdint.h>

//
// AUTOGENERATED BY BUILD
// DO NOT MODIFY - CHANGES WILL BE OVERWRITTEN
//

"""

DEFINITIONS_FILE = """#include <stdint.h>

//
// AUTOGENERATED BY BUILD
// DO NOT MODIFY - CHANGES WILL BE OVERWRITTEN
//

"""


def order_resource_objects(resos, resource_id_mapping=None):
    """Sort resource objects by storage type, preserving the order within
    each type. An explicit id mapping overrides the ordering entirely."""
    if resource_id_mapping:
        resos_dict = {resource_id_mapping[r.definition.name]: r for r in resos}
        return [resos_dict[i] for i in range(1, len(resos) + 1)]

    ordered = []
    for storage in (StorageType.pbpack, StorageType.builtin, StorageType.pfs):
        ordered.extend(r for r in resos if r.definition.storage == storage)
    return ordered


def build_resource_ball(reso_paths, output_path, declarations=(),
                        resource_id_mapping=None):
    resos = [ResourceObject.load(path) for path in reso_paths]
    ball = ResourceBall(
        order_resource_objects(resos, resource_id_mapping), list(declarations)
    )
    ball.dump(output_path)


def build_pbpack(ball_path, output_path, is_system=False):
    ball = ResourceBall.load(ball_path)
    pack = ResourcePack(is_system)
    for reso in ball.resource_objects:
        if reso.definition.storage == StorageType.pbpack:
            pack.add_resource(reso.data)
    with open(output_path, "wb") as f:
        pack.serialize(f)


def build_builtin(ball_path, output_path, resource_id_include):
    ball = ResourceBall.load(ball_path)
    resos = [
        r for r in ball.resource_objects
        if r.definition.storage == StorageType.builtin
    ]

    def var_name(reso):
        return f"{reso.definition.name}_builtin_bytes"

    with open(output_path, "w") as f:
        f.write(f'#include "{resource_id_include}"\n')
        f.write('#include "resource/resource_storage.h"\n')
        f.write('#include "resource/resource_storage_builtin.h"\n\n')

        for reso in resos:
            # Some resources require 8-byte aligned addresses; aligning them
            # all keeps the handling simple.
            f.write("__attribute__ ((aligned (8)))\n")
            generate_c_byte_array.write(f, reso.data, var_name(reso))

        f.write("\n")
        f.write(f"const uint32_t g_num_builtin_resources = {len(resos)};\n")
        f.write("const BuiltInResourceData g_builtin_resources[] = {\n")
        for reso in resos:
            f.write(
                "  {{ RESOURCE_ID_{name}, {var}, sizeof({var}) }},\n".format(
                    name=reso.definition.name, var=var_name(reso)
                )
            )
        f.write("};\n")


def build_resource_id_header(ball_path, output_path, use_extern=False,
                             use_define=False, published_media=()):
    if use_extern:
        resource_id_decl = "extern uint32_t RESOURCE_ID_{};"
        published_id_decl = "extern uint32_t PUBLISHED_ID_{};"
    elif use_define:
        resource_id_decl = "#define  RESOURCE_ID_{}  {}"
        published_id_decl = "#define  PUBLISHED_ID_{}  {}"
    else:
        resource_id_decl = "  RESOURCE_ID_{} = {},"
        invalid_resource_id_decl = "  RESOURCE_ID_{} = INVALID_RESOURCE,"
        if published_media:
            raise ValueError(
                "publishedMedia is only supported for resource headers using "
                "externs and defines."
            )

    ball = ResourceBall.load(ball_path)
    declarations_dict = {d.name: d for d in ball.get_all_declarations()}

    with open(output_path, "w") as f:
        if use_extern:
            f.write(EXTERN_HEADER)
        elif use_define:
            f.write(DEFINE_HEADER)
        else:
            f.write(ENUM_HEADER)

        # Write out all the fonts and their aliases
        for i, declaration in enumerate(ball.get_all_declarations(), start=1):
            f.write(resource_id_decl.format(declaration.name, i) + "\n")
            if isinstance(declaration, ResourceDefinition):
                f.writelines(
                    resource_id_decl.format(alias, i) + " // alias\n"
                    for alias in declaration.aliases
                )
        f.writelines(
            published_id_decl.format(item["name"], item["id"] or 0) + "\n"
            for item in published_media
        )

        if use_extern or use_define:
            return

        # Every font needs a matching extended id; generate a fake one for
        # the extended fonts that do not exist as a resource.
        def write_invalid_id_if_needed(name):
            extended_name = name + "_EXTENDED"
            if extended_name not in declarations_dict:
                f.write(invalid_resource_id_decl.format(extended_name) + "\n")

        for reso in ball.resource_objects:
            if reso.definition.type == "font":
                write_invalid_id_if_needed(reso.definition.name)
                for alias in reso.definition.aliases:
                    write_invalid_id_if_needed(alias)
        f.write("} ResourceId;")


def build_resource_id_definitions(ball_path, output_path, published_media=()):
    ball = ResourceBall.load(ball_path)
    with open(output_path, "w") as f:
        f.write(DEFINITIONS_FILE)
        for i, declaration in enumerate(ball.get_all_declarations(), start=1):
            f.write(f"uint32_t RESOURCE_ID_{declaration.name} = {i};\n")
            if isinstance(declaration, ResourceDefinition):
                f.writelines(
                    f"uint32_t RESOURCE_ID_{alias} = {i}; // alias\n"
                    for alias in declaration.aliases
                )
        f.writelines(
            "uint32_t PUBLISHED_ID_{} = {};".format(item["name"], item["id"])
            for item in published_media
        )


def font_keys(ball_path):
    ball = ResourceBall.load(ball_path)
    keys = []
    for definition in (o.definition for o in ball.resource_objects):
        if definition.type == "font":
            keys.append(definition.name)
            keys.extend(definition.aliases)
    return keys


def build_font_header(ball_path, output_path):
    with open(output_path, "w") as f:
        f.write("#pragma once\n\n")
        f.writelines(
            f'#define FONT_KEY_{key} "RESOURCE_ID_{key}"\n'
            for key in font_keys(ball_path)
        )
        # See PBL-9335. This define was removed as it is no longer a
        # complete font; it looked like Gothic 14, so use that instead.
        f.write('#define FONT_KEY_FONT_FALLBACK "RESOURCE_ID_GOTHIC_14"\n')


def build_font_table(ball_path, output_path):
    with open(output_path, "w") as f:
        f.write("""
static const struct {
  const char *key_name;
  ResourceId resource_id;
  ResourceId extension_id;
} s_font_resource_keys[] = {
""")
        f.writelines(
            f"  {{ FONT_KEY_{key}, RESOURCE_ID_{key}, "
            f"RESOURCE_ID_{key}_EXTENDED }},\n"
            for key in font_keys(ball_path)
        )
        f.write("};\n")


def build_timeline_table(timeline_dict, output_path):
    with open(output_path, "w") as f:
        f.write("""
//
// AUTOGENERATED
// DO NOT MODIFY
//

#include "resource/resource_ids.auto.h"
#include "pbl/services/timeline/timeline_resources.h"

#include <stdint.h>

const uint16_t g_timeline_resources[][TimelineResourceSizeCount] = {
""")
        f.writelines(
            "   [{}] = {{ {}, {}, {} }},\n".format(
                res["id"],
                res["sizes"].get("tiny", "RESOURCE_ID_INVALID"),
                res["sizes"].get("small", "RESOURCE_ID_INVALID"),
                res["sizes"].get("large", "RESOURCE_ID_INVALID"),
            )
            for res in timeline_dict
        )
        f.write("};\n")


def build_timeline_ids(timeline_dict, output_path):
    SYSTEM_RESOURCE_FLAG = 0x80000000
    with open(output_path, "w") as f:
        f.write("""
#pragma once

//
// AUTOGENERATED
// DO NOT MODIFY
//

typedef enum {
  TIMELINE_RESOURCE_INVALID = 0,
""")
        max_timeline_id = 0
        for res in timeline_dict:
            max_timeline_id = max(max_timeline_id, res["id"])
            f.write("  TIMELINE_RESOURCE_{} = {:#x},\n".format(
                res["name"], res["id"] | SYSTEM_RESOURCE_FLAG))
        f.write("} TimelineResourceId;\n\n")
        f.write(f"#define NUM_TIMELINE_RESOURCES {max_timeline_id + 1}\n")


def build_pfs_resource_table(file_definitions, output_path,
                             resource_id_include):
    with open(output_path, "w") as f:
        f.write("""
//
// AUTOGENERATED
// DO NOT MODIFY
//

#include "resource/resource_storage_file.h"
""")
        f.write(f'#include "{resource_id_include}"\n')
        f.write("\n")
        f.write(
            f"const uint32_t g_num_file_resource_stores = {len(file_definitions)};\n"
        )
        f.write("\n")
        f.write("const FileResourceData g_file_resource_stores[] = {\n")
        for d in file_definitions:
            first = "RESOURCE_ID_{}".format(d["resources"][0])
            last = "RESOURCE_ID_{}".format(d["resources"][-1])
            # FIXME: this offset is trivially computed at compile time; the
            # concept should just go away.
            f.write(f'  {{ {first}, {last}, ({first} - 1), "{d["name"]}" }},\n')
        f.write("};\n")


def build_version_header(output_path, pbpack_path=None):
    if pbpack_path:
        # is_system=True because only firmwares use version headers
        with open(pbpack_path, "rb") as f:
            resource_crc = ResourcePack.deserialize(f, is_system=True).get_content_crc()
    else:
        resource_crc = 0

    with open(output_path, "w") as f:
        f.write(f"""
#pragma once

//
// AUTOGENERATED
// DO NOT MODIFY
//

static const ResourceVersion SYSTEM_RESOURCE_VERSION = {{
  .crc = {resource_crc},
  .timestamp = 0
}};
""")
