/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <time.h>

#include <pbl/util/time.h>

/**
 * @defgroup services_time Time
 * @ingroup services
 * @brief Timezone, DST and local time conversions.
 *
 * Holds the current timezone and its DST period, set from the phone or the timezone database,
 * and converts between UTC and local time accordingly.
 * @{
 */

/**
 * @brief DST rule index of Brazil.
 *
 * DST ids index the rules generated by tools/timezones.py from the Olson database; do not change
 * them independently. Ids not listed here switch by one hour on the same spring and autumn days
 * every year. Morocco's rules, which suspend DST for Ramadan, are not handled correctly.
 */
#define DSTID_BRAZIL 6
/** @brief DST rule index of Lord Howe Island, whose DST offset is half an hour. */
#define DSTID_LORDHOWE 20

/** @brief Timezone information, small enough to be kept in RTC registers. */
typedef struct TimezoneInfo {
  /**
   * Abbreviation, up to 5 characters, not NUL terminated. A @c * is replaced by @c D or @c S
   * depending on DST.
   */
  char tm_zone[TZ_LEN - 1];
  /** DST rule index. */
  uint8_t dst_id;
  /** Olson index of the timezone. */
  int16_t timezone_id;
  /** Offset from UTC in seconds, without DST. */
  int32_t tm_gmtoff;
  /** UTC timestamp of the start of the DST period, 0 if none. */
  time_t dst_start;
  /** UTC timestamp of the end of the DST period, 0 if none. */
  time_t dst_end;
} TimezoneInfo;

/**
 * @brief Get the timezone abbreviation in effect at a given time.
 *
 * @param[out] out_buf Buffer of @c TZ_LEN bytes, receives a NUL terminated abbreviation.
 * @param utc_time Time used to decide whether DST applies.
 */
void time_get_timezone_abbr(char *out_buf, time_t utc_time);

/**
 * @brief Get the offset of the timezone from UTC, without DST.
 *
 * @return Offset in seconds.
 */
int32_t time_get_gmtoffset(void);

/**
 * @brief Check whether a time falls within the DST period.
 *
 * @param utc_time UTC time.
 * @return True if DST applies.
 */
bool time_get_isdst(time_t utc_time);

/**
 * @brief Get the offset added during DST.
 *
 * @return Offset in seconds, usually one hour.
 */
int32_t time_get_dstoffset(void);

/**
 * @brief Get the start of the DST period.
 *
 * @return UTC timestamp, 0 if none.
 */
time_t time_get_dst_start(void);

/**
 * @brief Convert UTC time, as returned by rtc_get_time(), to local time.
 *
 * @param utc_time UTC time.
 * @return Local time.
 */
time_t time_utc_to_local(time_t utc_time);

/**
 * @brief Convert local time to UTC time.
 *
 * Ambiguous during the hour repeated when DST ends.
 *
 * @param local_time Local time.
 * @return UTC time.
 */
time_t time_local_to_utc(time_t local_time);

/**
 * @brief Set the current timezone.
 *
 * @param tz_info New timezone, including its DST period.
 */
void time_util_update_timezone(const TimezoneInfo *tz_info);

/**
 * @brief Get the local midnight starting the day of a time.
 *
 * @param ts UTC time.
 * @return UTC time of the local midnight.
 */
time_t time_util_get_midnight_of(time_t ts);

/**
 * @brief Check whether a range covers a whole day.
 *
 * @param start Start of the range.
 * @param end End of the range.
 * @param start_of_day Start of the day.
 * @return True if the range covers the 24 hours from @p start_of_day.
 */
bool time_util_range_spans_day(time_t start, time_t end, time_t start_of_day);

/**
 * @brief Syscall wrapper of time_utc_to_local(), for unprivileged code.
 *
 * @param t UTC time.
 * @return Local time.
 */
time_t sys_time_utc_to_local(time_t t);

/**
 * @brief Get the current offset of local time from UTC, including DST.
 *
 * @return Offset in seconds.
 */
time_t time_util_utc_to_local_offset(void);

/**
 * @brief Get the local day index of a time.
 *
 * The index increments every day at local midnight.
 *
 * @param utc_sec UTC time.
 * @return Days since the epoch, in local time.
 */
uint16_t time_util_get_day(time_t utc_sec);

/**
 * @brief Get the local day of the week of a time.
 *
 * @param utc_sec UTC time.
 * @return Day of the week.
 */
enum pbl_weekday time_util_get_day_in_week(time_t utc_sec);

/**
 * @brief Get the local minute of the day of a time.
 *
 * @param utc_sec UTC time.
 * @return Minutes since local midnight.
 */
int time_util_get_minute_of_day(time_t utc_sec);

/**
 * @brief Return the UTC time that corresponds to the start of today (midnight).
 * @return the UTC time corresponding to the start of today (midnight)
 */
time_t time_start_of_today(void);

/**
 * @brief Get the time since boot.
 *
 * Based on the tick count, so unaffected by changes of the wall-clock time.
 *
 * @return Uptime in seconds.
 */
uint32_t time_get_uptime_seconds(void);

/** @} */
