# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0
#
# Kconfig-driven C library selection (see lib/c/Kconfig). Sets
# PBL_LIBC_LINK_FLAGS and PBL_LIBC_LIBS for the firmware link, and adds
# the flags that make the toolchain libc match what the firmware expects:
# 32-bit time_t, the integer-only printf aliases, and the POSIX/BSD names
# that -std=c11 would otherwise hide.

# newlib defaults time_t to 64-bit; keep it 32-bit (long) to match the
# firmware's RTC/storage and its %ld format strings.
set(pbl_newlib_time_define -D_USE_LONG_TIME_T)
# The firmware calls the integer-only printf names; map them onto the real
# ones (the historical in-tree libc aliased them in its headers).
set(pbl_sniprintf_defines -Dsniprintf=snprintf -Dvsniprintf=vsnprintf)
set(pbl_default_source_define -D_DEFAULT_SOURCE)

function(pbl_libc_add_flags)
  add_compile_options(${ARGN})
  add_link_options(${ARGN})
endfunction()

# picolibc hardcodes a 64-bit __time_t. The firmware wants 32-bit, to match
# its RTC/storage and %ld formats, so the same machine override is force
# included into both the picolibc build and the firmware; that keeps the
# ABI of the time_t-taking functions (mktime/localtime/...) consistent.
function(pbl_picolibc_time_override out)
  set(header ${PROJECT_BINARY_DIR}/picolibc/picolibc_machine_override.h)
  file(WRITE ${header}
"/* Generated by cmake/modules/libc.cmake. */
#ifndef _PBL_PICOLIBC_MACHINE_OVERRIDE_H
#define _PBL_PICOLIBC_MACHINE_OVERRIDE_H
/* picolibc force-includes this into .S files too; C-only. */
#ifndef __ASSEMBLER__
typedef long __time_t;
#define __machine_time_t_defined
#endif
#endif
")
  set(${out} ${header} PARENT_SCOPE)
endfunction()

function(pbl_arch_flags out)
  get_directory_property(flags COMPILE_OPTIONS)
  set(arch "")
  foreach(flag ${flags})
    if(flag MATCHES "^(-mthumb|-mcpu=|-mfloat-abi=|-mfpu=|-march=)")
      list(APPEND arch ${flag})
    endif()
  endforeach()
  set(${out} "${arch}" PARENT_SCOPE)
endfunction()

# Build third_party/picolibc for the current architecture; returns the
# specs file the compile and link lines then point at.
function(pbl_build_picolibc out)
  set(src ${PBL_BASE}/third_party/picolibc)
  if(NOT EXISTS ${src}/meson.build)
    message(FATAL_ERROR
      "third_party/picolibc submodule missing; run "
      "`git submodule update --init third_party/picolibc`")
  endif()
  find_program(MESON meson REQUIRED)
  find_program(NINJA ninja REQUIRED)

  set(out_dir ${PROJECT_BINARY_DIR}/picolibc)
  set(build_dir ${out_dir}/build)
  set(install_dir ${out_dir}/install)
  pbl_picolibc_time_override(override)
  pbl_arch_flags(arch)
  list(APPEND arch -include ${override})
  set(arch_literal "")
  foreach(flag ${arch})
    string(APPEND arch_literal "'${flag}', ")
  endforeach()

  file(WRITE ${out_dir}/cross.txt
"[binaries]
c = ['${CROSS_COMPILE}gcc', ${arch_literal}'-nostdlib']
cpp = ['${CROSS_COMPILE}g++', ${arch_literal}'-nostdlib']
ar = '${CROSS_COMPILE}ar'
as = '${CROSS_COMPILE}as'
nm = '${CROSS_COMPILE}nm'
strip = '${CROSS_COMPILE}strip'
[host_machine]
system = 'none'
cpu_family = 'arm'
cpu = 'arm'
endian = 'little'
[properties]
skip_sanity_check = true
")

  # A single architecture, no crt0 or semihosting (the firmware supplies
  # its own startup and syscalls), C99 + long long formatted I/O, and one
  # global TLS block (per-task TLS is a separate integration).
  if(NOT EXISTS ${build_dir}/build.ninja)
    message(STATUS "Configuring picolibc")
    execute_process(
      COMMAND ${MESON} setup ${build_dir} ${src}
        --cross-file ${out_dir}/cross.txt
        -Dspecsdir=${install_dir}/lib
        --prefix=${install_dir}
        -Dmultilib=false
        -Dpicocrt=false
        -Dsemihost=false
        -Dtests=false
        -Dio-long-long=true
        -Dformat-default=long-long
        -Dthread-local-storage=false
      COMMAND_ERROR_IS_FATAL ANY
    )
  endif()
  message(STATUS "Building picolibc")
  execute_process(COMMAND ${NINJA} -C ${build_dir} install
                  OUTPUT_QUIET COMMAND_ERROR_IS_FATAL ANY)

  set(specs ${install_dir}/lib/picolibc.specs)
  if(NOT EXISTS ${specs})
    message(FATAL_ERROR "picolibc build did not produce picolibc.specs")
  endif()
  # The firmware needs the same 32-bit time_t override picolibc built with.
  pbl_libc_add_flags("SHELL:-include ${override}")
  set(${out} ${specs} PARENT_SCOPE)
endfunction()

function(pbl_find_prebuilt_picolibc out)
  execute_process(
    COMMAND ${CMAKE_C_COMPILER} -print-file-name=picolibc.specs
    OUTPUT_VARIABLE specs
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
  # gcc echoes the name back unchanged when it cannot find the file.
  if(specs AND NOT specs STREQUAL "picolibc.specs" AND EXISTS ${specs})
    set(${out} ${specs} PARENT_SCOPE)
  else()
    set(${out} "" PARENT_SCOPE)
  endif()
endfunction()

if(CONFIG_LIBC_NEWLIB OR CONFIG_LIBC_NEWLIB_NANO)
  if(CONFIG_LIBC_NEWLIB_NANO)
    set(PBL_LIBC_LINK_FLAGS -nostartfiles -specs=nano.specs -specs=nosys.specs)
    message(STATUS "libc: newlib-nano")
  else()
    set(PBL_LIBC_LINK_FLAGS -nostartfiles -specs=nosys.specs)
    message(STATUS "libc: newlib")
  endif()
  set(PBL_LIBC_LIBS m gcc)
  pbl_libc_add_flags(${pbl_newlib_time_define} ${pbl_default_source_define}
                     ${pbl_sniprintf_defines})
elseif(CONFIG_LIBC_PICOLIBC)
  set(pbl_picolibc_specs "")
  if(NOT CONFIG_LIBC_PICOLIBC_FROM_SOURCE)
    pbl_find_prebuilt_picolibc(pbl_picolibc_specs)
    if(NOT pbl_picolibc_specs)
      message(WARNING
        "No pre-built picolibc in the toolchain (not using the PebbleOS SDK "
        "toolchain?); building picolibc from source (third_party/picolibc).")
    endif()
  endif()
  if(pbl_picolibc_specs)
    message(STATUS "libc: picolibc (pre-built)")
  else()
    pbl_build_picolibc(pbl_picolibc_specs)
    message(STATUS "libc: picolibc (from source)")
  endif()
  set(PBL_LIBC_LINK_FLAGS -nostartfiles)
  set(PBL_LIBC_LIBS m gcc)
  # picolibc.specs supplies both the headers (cpp -isystem) and the libc
  # link, so it belongs on the compile and the link line.
  pbl_libc_add_flags(-specs=${pbl_picolibc_specs} ${pbl_default_source_define}
                     ${pbl_sniprintf_defines})
else()
  message(FATAL_ERROR "No C library selected (see lib/c/Kconfig)")
endif()
