#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

"""Cell model fitting and replay for the fuel gauge (subsys/fuel_gauge).

See docs/architecture/fuel_gauge.md for the model and the workflow.

Logs are CSV files with the columns of LOG_COLUMNS: time [s], terminal
voltage [V], current [A, positive when discharging], temperature [C] and the
charge state given to the estimator (enum pbl_fuel_gauge_charge_state).
"""

import argparse
import csv
import ctypes
import dataclasses
import pathlib
import re
import subprocess
import sys
import tempfile

import numpy as np
from scipy import optimize

PBL_BASE = pathlib.Path(__file__).resolve().parent.parent

LOG_COLUMNS = ("time_s", "voltage_v", "current_a", "temperature_c", "charge_state")

DISCHARGING, CHARGING_CC, CHARGING_CV, CHARGE_COMPLETE = range(4)

T_REF_C = 25.0


@dataclasses.dataclass
class Log:
    t: np.ndarray
    v: np.ndarray
    i: np.ndarray
    temp: np.ndarray
    state: np.ndarray

    @property
    def dt(self):
        return np.diff(self.t, prepend=self.t[0])


@dataclasses.dataclass
class Model:
    name: str
    capacity_ah: float
    ocv_soc: np.ndarray
    ocv_v: np.ndarray
    r0: float
    r1: float
    tau1: float
    r_temp_coeff: float

    def ocv(self, soc):
        return np.interp(soc, self.ocv_soc, self.ocv_v)

    def r_scale(self, temp):
        return np.exp(self.r_temp_coeff * (T_REF_C - np.clip(temp, -20.0, 60.0)))


def read_log(path):
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    col = {c: np.array([float(r[c]) for r in rows]) for c in LOG_COLUMNS}
    return Log(
        col["time_s"],
        col["voltage_v"],
        col["current_a"],
        col["temperature_c"],
        col["charge_state"].astype(int),
    )


def write_log(path, log):
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(LOG_COLUMNS)
        for row in zip(log.t, log.v, log.i, log.temp, log.state):
            w.writerow(
                [
                    f"{row[0]:.3f}",
                    f"{row[1]:.4f}",
                    f"{row[2]:.6f}",
                    f"{row[3]:.2f}",
                    row[4],
                ]
            )


def write_model(path, m):
    points = [f"{{{s:.3f}f, {v:.4f}f}}," for s, v in zip(m.ocv_soc, m.ocv_v)]
    lines = [
        "/* SPDX-FileCopyrightText: 2026 Core Devices LLC */",
        "/* SPDX-License-Identifier: Apache-2.0 */",
        "",
        "// Generated by tools/fuel_gauge.py fit.",
        "",
        "#include <pbl/fuel_gauge/fuel_gauge.h>",
        "",
        "static const struct pbl_fuel_gauge_ocv_point s_ocv[] = {",
        *(f"  {p}" for p in points),
        "};",
        "",
        "const struct pbl_fuel_gauge_model battery_model = {",
        f'  .name = "{m.name}",',
        f"  .capacity_ah = {m.capacity_ah:.5f}f,",
        "  .ocv = s_ocv,",
        "  .ocv_count = sizeof(s_ocv) / sizeof(s_ocv[0]),",
        f"  .r0 = {m.r0:.4f}f,",
        f"  .r1 = {m.r1:.4f}f,",
        f"  .tau1 = {m.tau1:.1f}f,",
        f"  .r_temp_coeff = {m.r_temp_coeff:.4f}f,",
        "};",
        "",
    ]
    pathlib.Path(path).write_text("\n".join(lines))


# The estimator itself, built for the host and driven through ctypes, so the
# replay runs exactly the firmware code.


class _OcvPoint(ctypes.Structure):
    _fields_ = [("soc", ctypes.c_float), ("v", ctypes.c_float)]


class _Model(ctypes.Structure):
    _fields_ = [
        ("name", ctypes.c_char_p),
        ("capacity_ah", ctypes.c_float),
        ("ocv", ctypes.POINTER(_OcvPoint)),
        ("ocv_count", ctypes.c_uint8),
        ("r0", ctypes.c_float),
        ("r1", ctypes.c_float),
        ("tau1", ctypes.c_float),
        ("r_temp_coeff", ctypes.c_float),
    ]


class _Config(ctypes.Structure):
    _fields_ = [
        ("model", ctypes.POINTER(_Model)),
        ("voltage_noise", ctypes.c_float),
        ("current_noise", ctypes.c_float),
        ("term_voltage", ctypes.c_float),
        ("term_current", ctypes.c_float),
    ]


class _Meas(ctypes.Structure):
    _fields_ = [("v", ctypes.c_float), ("i", ctypes.c_float), ("t", ctypes.c_float)]


class Estimator:
    """The C estimator linked with a C cell model."""

    def __init__(self, model_c, workdir):
        lib = pathlib.Path(workdir) / "libfuel_gauge.so"
        subprocess.run(
            [
                "cc",
                "-shared",
                "-fPIC",
                "-O2",
                f"-I{PBL_BASE / 'include'}",
                str(PBL_BASE / "subsys/fuel_gauge/fuel_gauge.c"),
                str(model_c),
                "-o",
                str(lib),
                "-lm",
            ],
            check=True,
        )
        self._lib = ctypes.CDLL(str(lib))
        self._lib.pbl_fuel_gauge_update.restype = ctypes.c_float
        self._lib.pbl_fuel_gauge_soc_get.restype = ctypes.c_float
        self._c_model = _Model.in_dll(self._lib, "battery_model")
        self._fg = ctypes.create_string_buffer(256)

    @property
    def model(self):
        c = self._c_model
        points = [c.ocv[j] for j in range(c.ocv_count)]
        return Model(
            c.name.decode(),
            c.capacity_ah,
            np.array([p.soc for p in points]),
            np.array([p.v for p in points]),
            c.r0,
            c.r1,
            c.tau1,
            c.r_temp_coeff,
        )

    def run(self, log, voltage_noise, current_noise, term_voltage, term_current):
        """Returns the estimated and the reported SOC [0-1] of every sample."""
        self._config = _Config(
            ctypes.pointer(self._c_model),
            voltage_noise,
            current_noise,
            term_voltage,
            term_current,
        )
        meas = _Meas(log.v[0], log.i[0], log.temp[0])
        if (
            self._lib.pbl_fuel_gauge_init(
                self._fg, ctypes.byref(self._config), ctypes.byref(meas), None
            )
            < 0
        ):
            raise ValueError("invalid model or configuration")

        est = np.empty(len(log.t))
        reported = np.empty(len(log.t))
        for k, dt in enumerate(log.dt):
            meas = _Meas(log.v[k], log.i[k], log.temp[k])
            reported[k] = (
                self._lib.pbl_fuel_gauge_update(
                    self._fg, ctypes.byref(meas), ctypes.c_float(dt), int(log.state[k])
                )
                / 100.0
            )
            est[k] = self._lib.pbl_fuel_gauge_soc_get(self._fg)
        return est, reported


def coulomb_count(log, soc0, capacity_ah):
    """SOC from integrating the current, each sample covering the time since
    the previous one, as the estimator does."""
    return soc0 - np.cumsum(log.i * log.dt) / (capacity_ah * 3600.0)


def simulate(model, t, i, temp):
    """Terminal voltage and SOC of a cell starting full and at rest."""
    dt = np.diff(t, prepend=t[0])
    soc = coulomb_count(Log(t, None, i, temp, None), 1.0, model.capacity_ah)
    scale = model.r_scale(temp)
    v1 = _rc_filter(i * scale, dt, model.tau1) * model.r1
    return model.ocv(soc) - v1 - model.r0 * scale * i, soc


def _rc_filter(x, dt, tau):
    """First-order lag with x held over each step, as in the estimator."""
    a = np.exp(-dt / tau)
    y = np.empty_like(x)
    acc = 0.0
    for k in range(len(x)):
        acc = a[k] * acc + (1.0 - a[k]) * x[k]
        y[k] = acc
    return y


def _hat_weights(soc, grid):
    """Linear interpolation weights: OCV(soc) = W @ ocv_at_grid."""
    soc = np.clip(soc, grid[0], grid[-1])
    j = np.clip(np.searchsorted(grid, soc, side="right") - 1, 0, len(grid) - 2)
    f = (soc - grid[j]) / (grid[j + 1] - grid[j])
    w = np.zeros((len(soc), len(grid)))
    rows = np.arange(len(soc))
    w[rows, j] = 1.0 - f
    w[rows, j + 1] = f
    return w


class Fit:
    """Least-squares fit of the cell model to logs with a known SOC path.

    For a given tau1 and temperature coefficient the terminal voltage is
    linear in the unknowns:

        v = W(soc) @ ocv - R0 * s(T) * i - R1 * lag_tau1(s(T) * i)

    so each candidate is solved with bounded linear least squares, and tau1
    and the temperature coefficient are searched in an outer loop. The OCV
    points are written as a base voltage plus non-negative steps so the curve
    comes out increasing, and a second-difference penalty fills the SOC
    ranges the logs do not visit.
    """

    MIN_STEP_V = 1e-4

    def __init__(self, logs, socs, grid, smoothing):
        self.logs = logs
        self.grid = grid
        self.w = np.vstack([_hat_weights(s, grid) for s in socs])
        self.v = np.concatenate([log.v for log in logs])
        n = len(grid)
        self.steps = np.tril(np.ones((n, n)))
        d2 = np.diff(np.eye(n), 2, axis=0)
        weight = smoothing * np.sqrt(len(self.v) / n)
        self.reg = weight * d2 @ self.steps
        self.coverage = self.w.sum(axis=0)

    def solve(self, tau1, r_temp_coeff):
        n = len(self.grid)
        cols_r0, cols_r1 = [], []
        for log in self.logs:
            si = log.i * np.exp(
                r_temp_coeff * (T_REF_C - np.clip(log.temp, -20.0, 60.0))
            )
            cols_r0.append(-si)
            cols_r1.append(-_rc_filter(si, log.dt, tau1))
        a = np.column_stack(
            [self.w @ self.steps, np.concatenate(cols_r0), np.concatenate(cols_r1)]
        )
        a = np.vstack([a, np.column_stack([self.reg, np.zeros((len(self.reg), 2))])])
        b = np.concatenate([self.v, np.zeros(len(self.reg))])
        lb = np.full(n + 2, self.MIN_STEP_V)
        lb[0] = -np.inf
        lb[n:] = 0.0
        res = optimize.lsq_linear(a, b, bounds=(lb, np.inf), method="bvls")
        x = res.x
        resid = self.v - a[: len(self.v)] @ x
        return self.steps @ x[:n], x[n], x[n + 1], resid

    def best_tau(self, r_temp_coeff):
        def cost(log_tau):
            return np.mean(self.solve(np.exp(log_tau), r_temp_coeff)[3] ** 2)

        res = optimize.minimize_scalar(
            cost, bounds=(np.log(5.0), np.log(5000.0)), method="bounded"
        )
        return np.exp(res.x), res.fun


def fit_model(
    logs,
    name,
    grid,
    start_socs,
    capacity_ah=None,
    end_soc=0.0,
    r_temp_coeff=None,
    smoothing=0.01,
):
    """Fits a model to logs whose SOC path is known from coulomb counting.

    Without an explicit capacity, the first log must go from its start SOC to
    end_soc, and its net discharged charge defines the capacity.
    """
    if capacity_ah is None:
        log = logs[0]
        charge_ah = np.sum(log.i * log.dt) / 3600.0
        capacity_ah = charge_ah / (start_socs[0] - end_soc)

    socs = [coulomb_count(log, s0, capacity_ah) for log, s0 in zip(logs, start_socs)]
    fit = Fit(logs, socs, grid, smoothing)

    temps = np.concatenate([log.temp for log in logs])
    if r_temp_coeff is not None:
        coeff = r_temp_coeff
    elif np.ptp(temps) >= 10.0:
        res = optimize.minimize_scalar(
            lambda k: fit.best_tau(k)[1], bounds=(0.0, 0.08), method="bounded"
        )
        coeff = res.x
    else:
        coeff = 0.03
        print(
            "logs span less than 10 C: using the default resistance temperature coefficient",
            file=sys.stderr,
        )

    tau1, _ = fit.best_tau(coeff)
    ocv, r0, r1, resid = fit.solve(tau1, coeff)
    model = Model(name, capacity_ah, grid, ocv, r0, r1, tau1, coeff)
    return model, resid, fit.coverage


# Commands


def cmd_extract(args):
    """Battery state log lines from a firmware log to a CSV log."""
    line = re.compile(
        r"Battery state: v_mv: (-?\d+), i_ua: (-?\d+), t_mc: (-?\d+), td_ms: (\d+), fg: (\d+)"
    )
    t = 0.0
    rows = []
    for text in args.input.read_text(errors="replace").splitlines():
        m = line.search(text)
        if m is None:
            continue
        v_mv, i_ua, t_mc, td_ms, state = (int(g) for g in m.groups())
        t += td_ms / 1000.0
        rows.append((t, v_mv / 1000.0, i_ua / 1e6, t_mc / 1000.0, state))
    if not rows:
        sys.exit("no battery state lines found (enable verbose battery service logs)")
    write_log(args.output, Log(*(np.array(c) for c in zip(*rows))))
    print(f"{len(rows)} samples, {rows[-1][0] / 3600.0:.1f} h")


def cmd_fit(args):
    logs = [read_log(p) for p in args.logs]
    start_socs = args.start_soc or [1.0] * len(logs)
    if len(start_socs) != len(logs):
        sys.exit("give one --start-soc per log")
    grid = np.array(args.grid) if args.grid else np.linspace(0.0, 1.0, args.grid_points)

    model, resid, coverage = fit_model(
        logs,
        args.name,
        grid,
        start_socs,
        capacity_ah=args.capacity_ah,
        end_soc=args.end_soc,
        r_temp_coeff=args.r_temp_coeff,
        smoothing=args.smoothing,
    )

    write_model(args.output, model)
    print(f"capacity    {model.capacity_ah * 1000.0:.1f} mAh")
    print(f"r0          {model.r0 * 1000.0:.0f} mohm")
    print(f"r1          {model.r1 * 1000.0:.0f} mohm")
    print(f"tau1        {model.tau1:.0f} s")
    print(f"temp coeff  {model.r_temp_coeff:.4f} 1/C")
    print(
        f"residual    {np.sqrt(np.mean(resid**2)) * 1000.0:.1f} mV rms, {np.max(np.abs(resid)) * 1000.0:.1f} mV max"
    )
    for s, c in zip(grid, coverage):
        if c < 1.0:
            print(
                f"warning: no data near SOC {s:.2f}, OCV extrapolated", file=sys.stderr
            )


def _write_replay(path, log, est, reported, ref):
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["time_s", "soc", "soc_reported", "soc_reference"])
        for row in zip(
            log.t, est, reported, ref if ref is not None else [""] * len(est)
        ):
            w.writerow([f"{x:.4f}" if isinstance(x, float) else x for x in row])


def cmd_replay(args):
    log = read_log(args.log)
    with tempfile.TemporaryDirectory() as tmp:
        est_lib = Estimator(args.model, tmp)
        model = est_lib.model
        est, reported = est_lib.run(
            log,
            args.voltage_noise,
            args.current_noise,
            args.term_voltage,
            args.term_current,
        )

    ref = None
    if args.start_soc is not None:
        ref = coulomb_count(log, args.start_soc, model.capacity_ah)
        err = est - ref
        print(
            f"SOC error   {np.sqrt(np.mean(err**2)) * 100.0:.2f} % rms, {np.max(np.abs(err)) * 100.0:.2f} % max"
        )
        err = reported - ref
        print(
            f"reported    {np.sqrt(np.mean(err**2)) * 100.0:.2f} % rms, {np.max(np.abs(err)) * 100.0:.2f} % max"
        )
    print(
        f"final SOC   {est[-1] * 100.0:.1f} % (reported {reported[-1] * 100.0:.1f} %)"
    )

    if args.output:
        _write_replay(args.output, log, est, reported, ref)

    if args.plot:
        import matplotlib.pyplot as plt

        hours = log.t / 3600.0
        fig, (ax_v, ax_i, ax_soc) = plt.subplots(3, 1, sharex=True, figsize=(10, 8))
        ax_v.plot(hours, log.v)
        ax_v.set_ylabel("V")
        ax_i.plot(hours, log.i * 1000.0)
        ax_i.set_ylabel("mA")
        ax_soc.plot(hours, est * 100.0, label="estimate")
        ax_soc.plot(hours, reported * 100.0, label="reported")
        if ref is not None:
            ax_soc.plot(hours, ref * 100.0, "--", label="coulomb count")
        ax_soc.set_ylabel("SOC %")
        ax_soc.set_xlabel("h")
        ax_soc.legend()
        fig.tight_layout()
        if args.plot == "-":
            plt.show()
        else:
            fig.savefig(args.plot)


def pulse_profile(capacity_ah, rate_c, pulse_s, rest_s, sample_s):
    """Current of a pulsed discharge: a rest, then pulses at rate_c separated
    by rests, down to empty and a final rest."""
    i_pulse = rate_c * capacity_ah
    cycle = pulse_s + rest_s
    n_pulses = int(np.ceil(capacity_ah * 3600.0 / (i_pulse * pulse_s)))
    duration = rest_s + n_pulses * cycle
    t = np.arange(0.0, duration + sample_s, sample_s)
    phase = (t - rest_s) % cycle
    i = np.where((t > rest_s) & (phase > 0.0) & (phase <= pulse_s), i_pulse, 0.0)
    delivered = np.cumsum(i * np.diff(t, prepend=0.0))
    i[delivered > capacity_ah * 3600.0] = 0.0
    return t, i


def cmd_synth(args):
    """A pulsed discharge log of a known model, for testing the fit."""
    with tempfile.TemporaryDirectory() as tmp:
        model = Estimator(args.model, tmp).model
    t, i = pulse_profile(
        model.capacity_ah, args.rate, args.pulse, args.rest, args.sample
    )
    temp = np.full_like(t, args.temp)
    v, _ = simulate(model, t, i, temp)
    rng = np.random.default_rng(args.seed)
    v = v + rng.normal(0.0, args.noise, len(v))
    if args.lsb > 0.0:
        v = np.round(v / args.lsb) * args.lsb
    write_log(args.output, Log(t, v, i, temp, np.zeros(len(t), dtype=int)))
    print(f"{len(t)} samples, {t[-1] / 3600.0:.1f} h")


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("extract", help="convert firmware battery logs to a CSV log")
    p.add_argument("input", type=pathlib.Path)
    p.add_argument("output", type=pathlib.Path)
    p.set_defaults(func=cmd_extract)

    p = sub.add_parser("fit", help="fit a cell model to CSV logs")
    p.add_argument("logs", nargs="+", type=pathlib.Path)
    p.add_argument(
        "-o", "--output", type=pathlib.Path, required=True, help="C model file"
    )
    p.add_argument("--name", required=True)
    p.add_argument(
        "--start-soc",
        type=float,
        action="append",
        help="SOC at the start of each log (default 1)",
    )
    p.add_argument(
        "--end-soc",
        type=float,
        default=0.0,
        help="SOC at the end of the first log (default 0)",
    )
    p.add_argument(
        "--capacity-ah",
        type=float,
        help="capacity, instead of deriving it from the first log",
    )
    p.add_argument(
        "--r-temp-coeff",
        type=float,
        help="resistance temperature coefficient, instead of fitting it",
    )
    p.add_argument(
        "--grid-points",
        type=int,
        default=21,
        help="evenly spaced OCV points (default 21)",
    )
    p.add_argument(
        "--grid", type=float, nargs="+", help="explicit OCV SOC points, from 0 to 1"
    )
    p.add_argument(
        "--smoothing",
        type=float,
        default=0.01,
        help="OCV curvature penalty (default 0.01)",
    )
    p.set_defaults(func=cmd_fit)

    p = sub.add_parser("replay", help="run the estimator over a CSV log")
    p.add_argument("model", type=pathlib.Path, help="C model file")
    p.add_argument("log", type=pathlib.Path)
    p.add_argument(
        "--start-soc",
        type=float,
        help="known SOC at the start, for a coulomb-count reference",
    )
    p.add_argument("--voltage-noise", type=float, default=0.015)
    p.add_argument("--current-noise", type=float, default=0.005)
    p.add_argument("--term-voltage", type=float, default=4.35)
    p.add_argument("--term-current", type=float, default=0.019)
    p.add_argument(
        "-o", "--output", type=pathlib.Path, help="CSV with the SOC of every sample"
    )
    p.add_argument("--plot", help="plot to this image file, or - to show it")
    p.set_defaults(func=cmd_replay)

    p = sub.add_parser("synth", help="simulate a pulsed discharge of a model")
    p.add_argument("model", type=pathlib.Path, help="C model file")
    p.add_argument("output", type=pathlib.Path)
    p.add_argument(
        "--rate", type=float, default=0.5, help="pulse current [C] (default 0.5)"
    )
    p.add_argument(
        "--pulse",
        type=float,
        default=144.0,
        help="pulse length [s] (default 144: 2%% at 0.5C)",
    )
    p.add_argument(
        "--rest",
        type=float,
        default=900.0,
        help="rest after each pulse [s] (default 900)",
    )
    p.add_argument(
        "--sample", type=float, default=1.0, help="sample period [s] (default 1)"
    )
    p.add_argument("--temp", type=float, default=25.0)
    p.add_argument(
        "--noise", type=float, default=0.002, help="voltage noise [V] (default 0.002)"
    )
    p.add_argument(
        "--lsb", type=float, default=0.0, help="voltage quantization [V] (default none)"
    )
    p.add_argument("--seed", type=int, default=0)
    p.set_defaults(func=cmd_synth)

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
