# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

add_subdirectory(shared)
if(CONFIG_DEMO_APP_ACCEL_DEMO)
  add_subdirectory(accel_demo)
endif()
if(CONFIG_DEMO_APP_ACTION_MENU)
  add_subdirectory(action_menu)
endif()
if(CONFIG_DEMO_APP_ACTIVITY_DEMO)
  add_subdirectory(activity_demo)
endif()
if(CONFIG_DEMO_APP_ACTIVITY_TEST)
  add_subdirectory(activity_test)
endif()
if(CONFIG_DEMO_APP_AMB_LIGHT_READ)
  add_subdirectory(amb_light_read)
endif()
if(CONFIG_DEMO_APP_ANIMATED_DEMO)
  add_subdirectory(animated_demo)
endif()
if(CONFIG_DEMO_APP_APP_HEAP_DEMO)
  add_subdirectory(app_heap_demo)
endif()
if(CONFIG_DEMO_APP_BOUNCING_BOX_DEMO)
  add_subdirectory(bouncing_box_demo)
endif()
if(CONFIG_DEMO_APP_CLICK)
  add_subdirectory(click)
endif()
if(CONFIG_DEMO_APP_DATA_LOGGING_TEST)
  add_subdirectory(data_logging_test)
endif()
if(CONFIG_DEMO_APP_DEADLOCK)
  add_subdirectory(deadlock)
endif()
if(CONFIG_DEMO_APP_DIALOGS)
  add_subdirectory(dialogs)
endif()
if(CONFIG_DEMO_APP_DOUBLE_TAP_TEST)
  add_subdirectory(double_tap_test)
endif()
if(CONFIG_DEMO_APP_EMOJI_TEST)
  add_subdirectory(emoji_test)
endif()
if(CONFIG_DEMO_APP_EVENT_SERVICE)
  add_subdirectory(event_service)
endif()
if(CONFIG_DEMO_APP_EXIT)
  add_subdirectory(exit)
endif()
if(CONFIG_DEMO_APP_FLASH_DIAGNOSTIC)
  add_subdirectory(flash_diagnostic)
endif()
if(CONFIG_DEMO_APP_FLASH_PROF)
  add_subdirectory(flash_prof)
endif()
if(CONFIG_DEMO_APP_FONT_TEST)
  add_subdirectory(font_test)
endif()
if(CONFIG_DEMO_APP_FS_RESOURCES)
  add_subdirectory(fs_resources)
endif()
if(CONFIG_DEMO_APP_FW_UPDATE_PROGRESS_SIM)
  add_subdirectory(fw_update_progress_sim)
endif()
if(CONFIG_DEMO_APP_GDRAWMASK_DEMO)
  add_subdirectory(gdrawmask_demo)
endif()
if(CONFIG_DEMO_APP_GFX_TESTS)
  add_subdirectory(gfx_tests)
endif()
if(CONFIG_DEMO_APP_HRM_DEMO)
  add_subdirectory(hrm_demo)
endif()
if(CONFIG_DEMO_APP_IDL)
  add_subdirectory(idl)
endif()
if(CONFIG_DEMO_APP_KILL_BT)
  add_subdirectory(kill_bt)
endif()
if(CONFIG_DEMO_APP_KINO_LAYER)
  add_subdirectory(kino_layer)
endif()
if(CONFIG_DEMO_APP_LIGHT_CONFIG)
  add_subdirectory(light_config)
endif()
if(CONFIG_DEMO_APP_MENU)
  add_subdirectory(menu)
endif()
if(CONFIG_DEMO_APP_MENU_OVERFLOW)
  add_subdirectory(menu_overflow)
endif()
if(CONFIG_DEMO_APP_MENU_RIGHT_ICON)
  add_subdirectory(menu_right_icon)
endif()
if(CONFIG_DEMO_APP_MENU_ROUND)
  add_subdirectory(menu_round)
endif()
if(CONFIG_DEMO_APP_MORPH_SQUARE)
  add_subdirectory(morph_square)
endif()
if(CONFIG_DEMO_APP_MOVABLE_LINE)
  add_subdirectory(movable_line)
endif()
if(CONFIG_DEMO_APP_MPU_TEST)
  add_subdirectory(mpu_test)
endif()
if(CONFIG_DEMO_APP_MPU_VIOLATION_TEST)
  add_subdirectory(mpu_violation_test)
endif()
if(CONFIG_DEMO_APP_NUMBER_FIELD)
  add_subdirectory(number_field)
endif()
if(CONFIG_DEMO_APP_OPTION_MENU)
  add_subdirectory(option_menu)
endif()
if(CONFIG_DEMO_APP_PEBBLE_COLORS)
  add_subdirectory(pebble_colors)
endif()
if(CONFIG_DEMO_APP_PEBBLE_SHAPES)
  add_subdirectory(pebble_shapes)
endif()
if(CONFIG_DEMO_APP_PERSIST)
  add_subdirectory(persist)
endif()
if(CONFIG_DEMO_APP_PROFILE_MUTEXES)
  add_subdirectory(profile_mutexes)
endif()
if(CONFIG_DEMO_APP_PROGRESS)
  add_subdirectory(progress)
endif()
if(CONFIG_DEMO_APP_SCROLL)
  add_subdirectory(scroll)
endif()
if(CONFIG_DEMO_APP_SIMPLE_MENU)
  add_subdirectory(simple_menu)
endif()
if(CONFIG_DEMO_APP_STATUSBAR)
  add_subdirectory(statusbar)
endif()
if(CONFIG_DEMO_APP_STROKE_WIDTH)
  add_subdirectory(stroke_width)
endif()
if(CONFIG_DEMO_APP_SWAP_LAYER)
  add_subdirectory(swap_layer)
endif()
if(CONFIG_DEMO_APP_TEMPERATURE_DEMO)
  add_subdirectory(temperature_demo)
endif()
if(CONFIG_DEMO_APP_TEST_ARGS_RECEIVER)
  add_subdirectory(test_args_receiver)
endif()
if(CONFIG_DEMO_APP_TEST_ARGS_SENDER)
  add_subdirectory(test_args_sender)
endif()
if(CONFIG_DEMO_APP_TEST_BLUETOOTH)
  add_subdirectory(test_bluetooth)
endif()
if(CONFIG_DEMO_APP_TEST_CORE_DUMP)
  add_subdirectory(test_core_dump)
endif()
if(CONFIG_DEMO_APP_TEST_SYS_TIMER)
  add_subdirectory(test_sys_timer)
endif()
if(CONFIG_DEMO_APP_TEXT_CLIPPING)
  add_subdirectory(text_clipping)
endif()
if(CONFIG_DEMO_APP_TEXT_FLOW)
  add_subdirectory(text_flow)
endif()
if(CONFIG_DEMO_APP_TEXT_LAYOUT)
  add_subdirectory(text_layout)
endif()
if(CONFIG_DEMO_APP_TEXT_SPACING)
  add_subdirectory(text_spacing)
endif()
if(CONFIG_DEMO_APP_TIMELINE_PINS)
  add_subdirectory(timeline_pins)
endif()
if(CONFIG_DEMO_APP_TIMER)
  add_subdirectory(timer)
endif()
if(CONFIG_DEMO_APP_TRIGGER_ALARM)
  add_subdirectory(trigger_alarm)
endif()
if(CONFIG_DEMO_APP_VIBE_AND_LOGS)
  add_subdirectory(vibe_and_logs)
endif()
if(CONFIG_DEMO_APP_VIBE_SCORE)
  add_subdirectory(vibe_score)
endif()
if(CONFIG_DEMO_APP_VIBE_STRENGTH)
  add_subdirectory(vibe_strength)
endif()
