# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

subdir('shared')
if cfg.get('CONFIG_DEMO_APP_ACCEL_DEMO', false)
  subdir('accel_demo')
endif
if cfg.get('CONFIG_DEMO_APP_ACTION_MENU', false)
  subdir('action_menu')
endif
if cfg.get('CONFIG_DEMO_APP_ACTIVITY_DEMO', false)
  subdir('activity_demo')
endif
if cfg.get('CONFIG_DEMO_APP_ACTIVITY_TEST', false)
  subdir('activity_test')
endif
if cfg.get('CONFIG_DEMO_APP_AMB_LIGHT_READ', false)
  subdir('amb_light_read')
endif
if cfg.get('CONFIG_DEMO_APP_ANIMATED_DEMO', false)
  subdir('animated_demo')
endif
if cfg.get('CONFIG_DEMO_APP_APP_HEAP_DEMO', false)
  subdir('app_heap_demo')
endif
if cfg.get('CONFIG_DEMO_APP_BOUNCING_BOX_DEMO', false)
  subdir('bouncing_box_demo')
endif
if cfg.get('CONFIG_DEMO_APP_CLICK', false)
  subdir('click')
endif
if cfg.get('CONFIG_DEMO_APP_DATA_LOGGING_TEST', false)
  subdir('data_logging_test')
endif
if cfg.get('CONFIG_DEMO_APP_DEADLOCK', false)
  subdir('deadlock')
endif
if cfg.get('CONFIG_DEMO_APP_DIALOGS', false)
  subdir('dialogs')
endif
if cfg.get('CONFIG_DEMO_APP_DOUBLE_TAP_TEST', false)
  subdir('double_tap_test')
endif
if cfg.get('CONFIG_DEMO_APP_EMOJI_TEST', false)
  subdir('emoji_test')
endif
if cfg.get('CONFIG_DEMO_APP_EVENT_SERVICE', false)
  subdir('event_service')
endif
if cfg.get('CONFIG_DEMO_APP_EXIT', false)
  subdir('exit')
endif
if cfg.get('CONFIG_DEMO_APP_FLASH_DIAGNOSTIC', false)
  subdir('flash_diagnostic')
endif
if cfg.get('CONFIG_DEMO_APP_FLASH_PROF', false)
  subdir('flash_prof')
endif
if cfg.get('CONFIG_DEMO_APP_FONT_TEST', false)
  subdir('font_test')
endif
if cfg.get('CONFIG_DEMO_APP_FS_RESOURCES', false)
  subdir('fs_resources')
endif
if cfg.get('CONFIG_DEMO_APP_FW_UPDATE_PROGRESS_SIM', false)
  subdir('fw_update_progress_sim')
endif
if cfg.get('CONFIG_DEMO_APP_GDRAWMASK_DEMO', false)
  subdir('gdrawmask_demo')
endif
if cfg.get('CONFIG_DEMO_APP_GFX_TESTS', false)
  subdir('gfx_tests')
endif
if cfg.get('CONFIG_DEMO_APP_HRM_DEMO', false)
  subdir('hrm_demo')
endif
if cfg.get('CONFIG_DEMO_APP_IDL', false)
  subdir('idl')
endif
if cfg.get('CONFIG_DEMO_APP_KILL_BT', false)
  subdir('kill_bt')
endif
if cfg.get('CONFIG_DEMO_APP_KINO_LAYER', false)
  subdir('kino_layer')
endif
if cfg.get('CONFIG_DEMO_APP_LIGHT_CONFIG', false)
  subdir('light_config')
endif
if cfg.get('CONFIG_DEMO_APP_MENU', false)
  subdir('menu')
endif
if cfg.get('CONFIG_DEMO_APP_MENU_OVERFLOW', false)
  subdir('menu_overflow')
endif
if cfg.get('CONFIG_DEMO_APP_MENU_RIGHT_ICON', false)
  subdir('menu_right_icon')
endif
if cfg.get('CONFIG_DEMO_APP_MENU_ROUND', false)
  subdir('menu_round')
endif
if cfg.get('CONFIG_DEMO_APP_MORPH_SQUARE', false)
  subdir('morph_square')
endif
if cfg.get('CONFIG_DEMO_APP_MOVABLE_LINE', false)
  subdir('movable_line')
endif
if cfg.get('CONFIG_DEMO_APP_MPU_TEST', false)
  subdir('mpu_test')
endif
if cfg.get('CONFIG_DEMO_APP_MPU_VIOLATION_TEST', false)
  subdir('mpu_violation_test')
endif
if cfg.get('CONFIG_DEMO_APP_NUMBER_FIELD', false)
  subdir('number_field')
endif
if cfg.get('CONFIG_DEMO_APP_OPTION_MENU', false)
  subdir('option_menu')
endif
if cfg.get('CONFIG_DEMO_APP_PEBBLE_COLORS', false)
  subdir('pebble_colors')
endif
if cfg.get('CONFIG_DEMO_APP_PEBBLE_SHAPES', false)
  subdir('pebble_shapes')
endif
if cfg.get('CONFIG_DEMO_APP_PERSIST', false)
  subdir('persist')
endif
if cfg.get('CONFIG_DEMO_APP_PROFILE_MUTEXES', false)
  subdir('profile_mutexes')
endif
if cfg.get('CONFIG_DEMO_APP_PROGRESS', false)
  subdir('progress')
endif
if cfg.get('CONFIG_DEMO_APP_SCROLL', false)
  subdir('scroll')
endif
if cfg.get('CONFIG_DEMO_APP_SIMPLE_MENU', false)
  subdir('simple_menu')
endif
if cfg.get('CONFIG_DEMO_APP_STATUSBAR', false)
  subdir('statusbar')
endif
if cfg.get('CONFIG_DEMO_APP_STROKE_WIDTH', false)
  subdir('stroke_width')
endif
if cfg.get('CONFIG_DEMO_APP_SWAP_LAYER', false)
  subdir('swap_layer')
endif
if cfg.get('CONFIG_DEMO_APP_TEMPERATURE_DEMO', false)
  subdir('temperature_demo')
endif
if cfg.get('CONFIG_DEMO_APP_TEST_ARGS_RECEIVER', false)
  subdir('test_args_receiver')
endif
if cfg.get('CONFIG_DEMO_APP_TEST_ARGS_SENDER', false)
  subdir('test_args_sender')
endif
if cfg.get('CONFIG_DEMO_APP_TEST_BLUETOOTH', false)
  subdir('test_bluetooth')
endif
if cfg.get('CONFIG_DEMO_APP_TEST_CORE_DUMP', false)
  subdir('test_core_dump')
endif
if cfg.get('CONFIG_DEMO_APP_TEST_SYS_TIMER', false)
  subdir('test_sys_timer')
endif
if cfg.get('CONFIG_DEMO_APP_TEXT_CLIPPING', false)
  subdir('text_clipping')
endif
if cfg.get('CONFIG_DEMO_APP_TEXT_FLOW', false)
  subdir('text_flow')
endif
if cfg.get('CONFIG_DEMO_APP_TEXT_LAYOUT', false)
  subdir('text_layout')
endif
if cfg.get('CONFIG_DEMO_APP_TEXT_SPACING', false)
  subdir('text_spacing')
endif
if cfg.get('CONFIG_DEMO_APP_TIMELINE_PINS', false)
  subdir('timeline_pins')
endif
if cfg.get('CONFIG_DEMO_APP_TIMER', false)
  subdir('timer')
endif
if cfg.get('CONFIG_DEMO_APP_TRIGGER_ALARM', false)
  subdir('trigger_alarm')
endif
if cfg.get('CONFIG_DEMO_APP_VIBE_AND_LOGS', false)
  subdir('vibe_and_logs')
endif
if cfg.get('CONFIG_DEMO_APP_VIBE_SCORE', false)
  subdir('vibe_score')
endif
if cfg.get('CONFIG_DEMO_APP_VIBE_STRENGTH', false)
  subdir('vibe_strength')
endif
