name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  pull-requests: read

jobs:
  build-firmware:
    uses: ./.github/workflows/build-firmware.yml
    secrets: inherit

  build-prf:
    uses: ./.github/workflows/build-prf.yml
    secrets: inherit

  build-qemu:
    uses: ./.github/workflows/build-qemu.yml
    secrets: inherit

  build-qemu-sdkshell:
    uses: ./.github/workflows/build-qemu-sdkshell.yml
    secrets: inherit

  release:
    runs-on: ubuntu-24.04

    needs:
      - build-firmware
      - build-prf
      - build-qemu
      - build-qemu-sdkshell
    permissions:
      contents: write

    env:
      TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Collect release files
        run: |
          mkdir release
          find artifacts -type f -exec cp {} release/ \;
          ls -l release

      - name: Create release
        uses: softprops/action-gh-release@v3.0.2
        with:
          files: release/*

      - name: Publish release to eng-dash
        if: ${{ github.repository == 'coredevices/PebbleOS' }}
        uses: ./.github/actions/publish-engdash
        with:
          version: ${{ env.TAG }}
          token: ${{ secrets.ENGDASH_OTA_TOKEN }}
